var TRACK_JVM = {
  "id": "jvm",
  "label": "Memory Management",
  "icon": "jvm",
  "desc": "How memory works in Spring Boot services on GKE. Starts with dashboards, progresses through container memory budgets and Spring Boot internals, and reaches JVM diagnostic tools for deep investigation.",
  "levels": [
    {
      "num": 1, "name": "Foundations",
      "desc": "I know my app uses memory and I can see it. I can find the right dashboard, recognise symptoms, and escalate with useful information.",
      "scenarios": [
        "Reading Grafana memory panels and recognising healthy vs unhealthy patterns",
        "Understanding OOMKilled — what it means and how to spot it",
        "Recognising memory configuration in deployment manifests (-Xmx, resource limits)",
        "Understanding Spring Boot warm-up and why first requests are slow",
        "Having a basic mental model of heap, stack, GC, and OutOfMemoryError"
      ]
    },
    {
      "num": 2, "name": "Practitioner",
      "desc": "I understand the container memory budget. When a pod gets OOMKilled, I can figure out whether it's heap or container sizing, and configure a new service correctly.",
      "scenarios": [
        "Sizing JVM memory for containers: heap + Metaspace + threads + buffers must fit the limit",
        "Applying the 60-70% rule and understanding why -Xmx = container limit causes OOMKill",
        "Recognising non-heap memory growth when heap looks healthy but pod memory climbs",
        "Reading kubectl describe pod after OOMKill and correlating with JVM config",
        "Understanding UseContainerSupport and Kubernetes resource requests vs limits"
      ]
    },
    {
      "num": 3, "name": "Adept",
      "desc": "I know where memory goes inside a Spring Boot app. I can reason about consumers and make informed configuration and code review decisions.",
      "scenarios": [
        "Reasoning about Spring Boot memory consumers: HikariCP, Kafka buffers, Tomcat threads, caches",
        "Reading Actuator memory metrics and correlating with behaviour",
        "Distinguishing OutOfMemoryError types: heap space, Metaspace, unable to create native thread",
        "Flagging memory risks in code reviews: unbounded collections, missing eviction, batch accumulation",
        "Estimating a service's memory footprint from its configuration"
      ]
    },
    {
      "num": 4, "name": "Veteran",
      "desc": "I can find root causes using JVM diagnostic tools. Dashboard observation isn't enough — I look inside the JVM to find leaks, GC pressure, and contention.",
      "scenarios": [
        "Analysing heap dumps with Eclipse MAT to find memory leaks and retained objects",
        "Reading GC logs to identify promotion rate, pause patterns, and old-gen growth",
        "Using JFR to profile allocation hotspots and correlate with GC pressure",
        "Interpreting thread dumps to diagnose contention and pool exhaustion",
        "Investigating Metaspace growth and class loader leaks"
      ]
    },
    {
      "num": 5, "name": "Expert",
      "desc": "I design for memory efficiency and set standards. Proactive decisions that prevent memory problems across services.",
      "scenarios": [
        "Evaluating G1 vs ZGC for production SLAs with JFR data",
        "Designing memory budgets across thread pools and connection pools",
        "Diagnosing cold start memory dimensions and designing readiness strategies",
        "Defining org-wide JVM configuration baselines",
        "Assessing Java version upgrade memory implications"
      ]
    },
    {
      "num": 6, "name": "Authority",
      "desc": "I own memory strategy for the engineering organisation. Platform observability, capacity planning, SLA budgets, and technology roadmap.",
      "scenarios": [
        "Designing fleet-wide memory reliability strategy and driving adoption",
        "Translating memory behaviour into SLA performance budgets",
        "Evaluating emerging JVM capabilities (virtual threads, CRaC, GraalVM AOT)",
        "Building fleet-wide memory observability and automated diagnostics",
        "Leading deep production investigations involving native memory or driver-level issues"
      ]
    }
  ],
  "questions": [
    {"level":1,"diff":1,"scenario":0,"q":"In a Grafana JVM dashboard, 'Used Heap' shows a sawtooth pattern — rises then drops sharply, over and over. What does this pattern indicate?","opts":["A memory leak — objects are not being collected","Normal healthy behaviour — heap rises as objects are allocated, then drops when GC runs","The service is crashing and restarting repeatedly","GC is misconfigured","The heap is too small"],"ans":1,"fb":"The sawtooth pattern is the signature of healthy garbage collection: objects are allocated (heap rises), GC runs and reclaims short-lived objects (heap drops sharply), and the cycle repeats. A memory leak would show a pattern where each trough is higher than the last — the baseline rises over time."},
    {"level":1,"diff":2,"scenario":0,"q":"In Grafana, 'Used Heap' climbs steadily over 6 hours without any drops. What does this pattern suggest?","opts":["Normal behaviour — the heap hasn't filled up yet so GC hasn't run","A memory leak — objects are being retained and GC cannot reclaim them","The service is idle with no traffic","GC is disabled","The dashboard is stale"],"ans":1,"fb":"Steady heap growth without drops means GC is running but cannot reclaim enough memory — objects are being retained by references the GC cannot clear. Normal behaviour produces a sawtooth pattern with periodic drops. GC runs automatically; it cannot be disabled in normal operation."},
    {"level":1,"diff":3,"scenario":0,"q":"A Grafana panel shows 'GC Pause Duration' spiking to 500ms every few minutes. The 'Used Heap' sawtooth looks normal. What is the immediate concern?","opts":["Nothing — GC pauses are normal","Application threads are frozen for 500ms during each pause, causing latency spikes for API callers","The service is about to crash","The heap is too large","The dashboard time range is too narrow"],"ans":1,"fb":"GC pauses are stop-the-world events — all application threads freeze while GC runs. A 500ms pause directly translates to a 500ms latency spike for any request in progress. G1GC's default target is 200ms — 500ms pauses indicate the heap may be too large or GC needs tuning."},

    {"level":1,"diff":1,"scenario":1,"q":"A GKE pod is restarting repeatedly with exit code 137. What happened?","opts":["The liveness probe failed","The JVM threw an unhandled exception","The container was OOM-killed by the Linux kernel — it exceeded its memory limit","The pod exceeded its CPU limit","A deployment rollback was triggered"],"ans":2,"fb":"Exit code 137 = killed by signal 9 (SIGKILL). The Linux OOM killer sends SIGKILL when a container's memory usage exceeds its cgroup limit. Liveness probe failures show different events in kubectl describe. CPU throttling slows the pod but does not kill it."},
    {"level":1,"diff":2,"scenario":1,"q":"A pod was OOM-killed (exit code 137). The JVM logs do NOT show OutOfMemoryError. How is this possible?","opts":["It's not possible — OOMKill always produces an OutOfMemoryError first","The kernel killed the container before the JVM detected it — OOMKill is external to the JVM","The logs were lost during the restart","The JVM suppressed the error","The OOM-kill was for a different container in the pod"],"ans":1,"fb":"OOMKill (exit 137) and OutOfMemoryError are different mechanisms. OutOfMemoryError is the JVM detecting it cannot allocate heap. OOMKill is the Linux kernel detecting the entire container process exceeds its memory limit. OOMKill can happen when non-heap memory pushes total memory past the limit — the JVM heap may be fine."},
    {"level":1,"diff":3,"scenario":1,"q":"A service restarts 3 times per day with exit code 137, always during peak traffic. Heap dashboards show the heap is only 60% full when restarts happen. What should you investigate?","opts":["The heap is too small — increase -Xmx","Non-heap memory (thread stacks, Kafka buffers, native memory) is growing under load and pushing total process memory past the container limit","The liveness probe is too aggressive during peak traffic","The service is CPU throttled, not memory constrained","Cloud SQL is rejecting connections during peak"],"ans":1,"fb":"Heap at 60% but container OOM-killed means the problem is outside the heap. Under peak traffic: more Tomcat threads (each ~1MB stack), more Kafka consumer buffers, JIT-compiled code — all grow. Total JVM memory = heap + Metaspace + thread stacks + direct buffers + native. If -Xmx is set too close to the container limit, there's no room for non-heap growth under load."},

    {"level":1,"diff":1,"scenario":2,"q":"In a Kubernetes deployment manifest, what does -Xmx512m control?","opts":["The container's total memory limit","The maximum heap memory the JVM can allocate","The amount of CPU allocated to the JVM","The number of threads the JVM can create","The maximum size of a single object"],"ans":1,"fb":"-Xmx512m sets the maximum Java heap size to 512 megabytes. The heap is where Java objects live. It does NOT control total JVM memory (which also includes Metaspace, thread stacks, and native memory) and it is NOT the container limit (set via resources.limits.memory)."},
    {"level":1,"diff":2,"scenario":2,"q":"A deployment manifest shows resources.limits.memory: 1Gi and the JVM flag -Xmx900m. Is this a good configuration?","opts":["Yes — the heap should use as much of the limit as possible","No — this leaves only ~124MB for Metaspace, thread stacks, direct byte buffers, and native memory, which is likely not enough","No — -Xmx should always equal the memory limit exactly","Yes — the 100MB headroom is standard","It depends on the CPU allocation"],"ans":1,"fb":"Total JVM memory = heap (900MB) + Metaspace (~80-150MB) + thread stacks (threads x ~1MB) + direct byte buffers + JIT code cache + native allocations. With a 1Gi limit and 900MB heap, only ~124MB remains. Under load this is almost certainly insufficient. Safe rule: -Xmx should be 60-70% of the container limit."},
    {"level":1,"diff":3,"scenario":2,"q":"You see -XX:+UseContainerSupport in a JVM configuration. What does this flag do?","opts":["Enables Spring Boot to detect it's running in Docker","Tells the JVM to read memory and CPU limits from the container's cgroup instead of the host machine","Enables Kubernetes health probes for the JVM","Optimises GC for containerised environments","Enables JFR recording in containers"],"ans":1,"fb":"Without container support, the JVM reads the host machine's total memory (e.g., 32GB on a GKE node) and may set its heap accordingly — far exceeding the container's actual limit. With UseContainerSupport, the JVM reads cgroup limits. This flag is on by default since Java 8u191 and Java 11+."},

    {"level":1,"diff":1,"scenario":3,"q":"A Spring Boot service takes 15 seconds to start. During those first 15 seconds, API response times are 2-3x higher than normal. Why?","opts":["The database is slow during startup","The JVM's JIT compiler hasn't yet optimised hot code paths — it runs in interpreted mode initially","The service is downloading dependencies at startup","Kubernetes is throttling CPU during startup","The readiness probe is misconfigured"],"ans":1,"fb":"The JVM initially runs bytecode through an interpreter. The JIT compiler identifies hot methods and compiles them to native machine code over time. Until hot paths are compiled, they run significantly slower. Spring context initialisation, connection pool creation, and Kafka rebalance also add to startup time."},
    {"level":1,"diff":2,"scenario":3,"q":"A freshly deployed pod passes its readiness probe but the first 50 API requests have 3x higher latency. What is happening?","opts":["The pod has a memory leak that only appears under initial load","The JVM is still warming up — JIT compilation, connection pool creation, and cache population haven't completed yet","The Kubernetes scheduler placed it on an overloaded node","The container image is being downloaded during these requests","The database needs to warm its cache for this pod"],"ans":1,"fb":"Readiness probes check basic health (e.g., /actuator/health returns UP), but the JVM isn't fully warm yet. JIT hasn't compiled hot paths, HikariCP may create connections lazily, Spring caches are empty, and Kafka consumers may still be rebalancing."},

    {"level":1,"diff":1,"scenario":4,"q":"What is 'garbage collection' in the JVM?","opts":["A background process that deletes unused files from the container's filesystem","The JVM's automatic process of identifying and reclaiming memory occupied by objects that are no longer referenced","A manual cleanup developers must trigger by calling System.gc()","A process that removes unused Docker images from the node","A Kubernetes feature that evicts idle pods"],"ans":1,"fb":"Garbage collection (GC) is the JVM's automatic memory management. It identifies objects in heap memory that are no longer reachable from any active reference chain and reclaims that memory for new allocations. Developers do not need to call it manually."},
    {"level":1,"diff":2,"scenario":4,"q":"A log shows java.lang.OutOfMemoryError: Java heap space. What does this mean?","opts":["The Linux kernel killed the container","The JVM could not allocate a new object because the heap is full and GC could not free enough space","The JVM ran out of thread stack space","The container's disk is full","Metaspace is exhausted"],"ans":1,"fb":"'Java heap space' means the garbage collector ran but could not free enough heap memory for a new allocation. This is different from OOMKill (exit 137). Metaspace exhaustion produces 'OutOfMemoryError: Metaspace'. Thread issues produce 'unable to create native thread'."},
    {"level":1,"diff":3,"scenario":4,"q":"What is the difference between OutOfMemoryError: Java heap space and the pod being OOM-killed (exit code 137)?","opts":["They are the same thing","OutOfMemoryError is the JVM detecting it can't allocate heap; OOMKill is the Linux kernel killing the container for exceeding its memory limit — they can happen independently","OutOfMemoryError always causes an OOMKill","OOMKill always produces an OutOfMemoryError first","OutOfMemoryError is for CPU; OOMKill is for memory"],"ans":1,"fb":"These are separate mechanisms at different layers. OutOfMemoryError: the JVM's internal check. OOMKill: the Linux kernel's enforcement. You can have OOMKill without OutOfMemoryError (non-heap exceeds limit while heap is fine). You can have OutOfMemoryError without OOMKill (heap full but total memory under limit)."},

    {"level":2,"diff":1,"scenario":0,"q":"A Spring Boot service runs in a container with 1Gi memory limit. The JVM uses heap, Metaspace, thread stacks, direct byte buffers, and native memory. What must be true?","opts":["Only the heap needs to fit within 1Gi","The sum of all JVM memory regions must fit within 1Gi, not just the heap","Metaspace and thread stacks are outside the container limit","Kubernetes automatically adjusts the limit for non-heap memory","The JVM manages the container limit automatically"],"ans":1,"fb":"The container memory limit (enforced by Linux cgroups) applies to the entire process. Total = heap + Metaspace + thread stacks (each ~1MB) + direct byte buffers + JIT code cache + native allocations. If this total exceeds the container limit, the kernel sends SIGKILL (exit 137)."},
    {"level":2,"diff":2,"scenario":0,"q":"You are sizing a new service. It has 200 Tomcat threads, 10 HikariCP connections, 3 Kafka consumers (50MB fetch buffer each). Estimated Metaspace is 120MB. What is the minimum non-heap memory needed?","opts":["About 120MB (just Metaspace)","About 200MB (Metaspace + some buffers)","About 520MB (200 threads x 1MB stacks + 150MB Kafka buffers + 120MB Metaspace + overhead)","About 50MB (non-heap is always small)","Impossible to estimate without a heap dump"],"ans":2,"fb":"Thread stacks: 200 x ~1MB = 200MB. Kafka buffers: 3 x 50MB = 150MB (direct byte buffers). Metaspace: 120MB. Plus JIT code cache (~50MB), native overhead. Total non-heap ~520MB+. If container limit is 1.5Gi, that leaves ~1GB for heap."},
    {"level":2,"diff":3,"scenario":0,"q":"A service has -Xmx=600m in a 1Gi container. After adding a new Kafka consumer group (5 threads, 50MB fetch.max.bytes each), the pod starts getting OOM-killed. Heap dashboards look normal. Why?","opts":["The heap is too small for the new consumer's messages","The 5 new Kafka consumers added ~250MB of direct byte buffer memory, pushing total JVM memory past the 1Gi container limit","Kafka is incompatible with the current JVM version","The new consumer group is causing GC pressure","The liveness probe is failing due to Kafka connectivity"],"ans":1,"fb":"Kafka consumer buffers (fetch.max.bytes) are allocated as direct byte buffers — outside the heap. 5 consumers x 50MB = 250MB off-heap. Before: 600MB heap + ~300MB non-heap = ~900MB. After: +250MB = ~1.15Gi > 1Gi → OOMKill."},

    {"level":2,"diff":1,"scenario":1,"q":"Why should -Xmx be set to 60-70% of the container memory limit, not 100%?","opts":["The JVM doesn't use all the heap anyway","The remaining 30-40% is needed for non-heap memory: Metaspace, thread stacks, direct byte buffers, JIT code cache, and native memory","Kubernetes reserves 30% for system processes","The GC needs 30% headroom to function","It's just a convention with no technical basis"],"ans":1,"fb":"The JVM uses significantly more memory than just the heap. Metaspace (~80-200MB), thread stacks (each ~1MB), direct byte buffers (NIO, Kafka, Netty), JIT compiled code cache (~50-240MB), and native allocations all live outside the heap but inside the container's memory limit."},
    {"level":2,"diff":2,"scenario":1,"q":"A team sets -Xmx equal to resources.limits.memory (both 2Gi). The service OOM-kills on every deployment but works at steady state. What explains this?","opts":["Deployments use more memory than steady state","During deployment, the JVM starts with heap + Metaspace for class loading + JIT compilation. Since -Xmx=2Gi and limit=2Gi, there is zero room for non-heap — any Metaspace or native allocation pushes past the limit","The deployment manifest is incorrect","Kubernetes doubles memory usage during rolling updates","The readiness probe causes extra memory allocation"],"ans":1,"fb":"At startup, the JVM allocates heap (reserves 2Gi), loads classes into Metaspace (100-200MB), creates thread stacks, and JIT-compiles code. Since 2Gi heap + any non-heap > 2Gi limit, the kernel kills the process before it finishes starting."},
    {"level":2,"diff":3,"scenario":1,"q":"Two identically configured services (-Xmx=512m, limit=1Gi) but one is OOM-killed weekly while the other never is. What is the most likely difference?","opts":["Different JVM versions","One service has more active threads, Kafka consumers, or larger caches — its non-heap memory footprint is higher, exhausting the headroom between heap and container limit","The OOM-killed service has a heap memory leak","They must be on different GKE node types","Cloud SQL is configured differently"],"ans":1,"fb":"With identical -Xmx and container limits, the difference must be in non-heap consumption. Service A might have 50 threads (50MB stacks) + 5 Kafka consumers (250MB). Service B might have 200 threads (200MB) + 10 Kafka consumers (500MB). Same config, very different non-heap footprints."},

    {"level":2,"diff":1,"scenario":2,"q":"Grafana shows JVM heap at 55% utilisation, but container memory usage is at 92%. What is consuming the remaining memory?","opts":["The heap metric is wrong","Non-heap JVM memory: Metaspace, thread stacks, direct byte buffers, JIT code cache, and native allocations","Kubernetes overhead","Other containers in the pod (e.g., sidecar)","Disk cache"],"ans":1,"fb":"JVM heap metrics only show heap. Container memory shows everything the process uses. The gap is non-heap: Metaspace, thread stacks, direct byte buffers, JIT-compiled code, and native allocations."},
    {"level":2,"diff":2,"scenario":2,"q":"A service's container memory usage grows slowly over days while heap usage stays stable. What are the most likely non-heap culprits?","opts":["Heap fragmentation","Metaspace growth (dynamic class loading) or direct byte buffer accumulation (connection/buffer leaks in NIO or Kafka)","GC pressure causing memory fragmentation","Kafka consumer lag","Increasing request payload sizes"],"ans":1,"fb":"Stable heap + growing container memory means something outside the heap is growing. Top candidates: Metaspace (dynamic class generation), direct byte buffers (Kafka/Netty not releasing buffers), or thread count growing (leaked thread pools)."},
    {"level":2,"diff":3,"scenario":2,"q":"After adding a new @Cacheable method using Spring's default ConcurrentMapCacheManager, heap usage grows linearly over weeks. What is the root cause?","opts":["The cache eviction policy is too aggressive","Spring's default ConcurrentMapCacheManager has no size limit or eviction — entries accumulate indefinitely","GC is not running frequently enough","The cache key is too large","The @Cacheable annotation is on the wrong method"],"ans":1,"fb":"Spring's default ConcurrentMapCacheManager uses a plain ConcurrentHashMap with no maximum size, no TTL, and no eviction. Every unique cache key adds an entry permanently. Fix: switch to Caffeine cache with maximumSize and expireAfterWrite."},

    {"level":2,"diff":1,"scenario":3,"q":"After an OOMKill, you run kubectl describe pod. What fields tell you the container exceeded its memory limit?","opts":["The pod's CPU usage section","'Last State: Terminated', 'Reason: OOMKilled', 'Exit Code: 137', and the container's memory limit in the resources section","The pod's event log only","The node's disk usage","The container's image version"],"ans":1,"fb":"kubectl describe pod shows 'Last State: Terminated, Reason: OOMKilled, Exit Code: 137'. The resources section shows limits.memory — the ceiling that was exceeded. Next step: correlate with JVM heap dashboards to determine heap vs non-heap cause."},
    {"level":2,"diff":2,"scenario":3,"q":"A pod shows OOMKilled in kubectl describe, but the JVM's last log line before the kill was a normal request completion — no OutOfMemoryError. What does this tell you?","opts":["The logs are incomplete","The JVM heap was fine — the OOMKill was caused by non-heap memory pushing total process memory past the container limit","The OOMKill was for a different container in the pod","The JVM suppressed the error","The container was killed for CPU, not memory"],"ans":1,"fb":"If the JVM didn't throw OutOfMemoryError, the heap had room. The OOMKill was triggered by total process memory (heap + non-heap) exceeding the container limit. The kernel kills instantly — the JVM has no chance to log."},

    {"level":2,"diff":1,"scenario":4,"q":"What does UseContainerSupport do for a JVM on GKE?","opts":["Enables health probes","Makes the JVM read memory and CPU limits from the container's cgroup instead of the host node's total resources","Optimises GC for containers","Enables JFR in containers","Allows the JVM to use swap memory"],"ans":1,"fb":"Without container support, a JVM on a 32GB GKE node would see 32GB and auto-size its heap to 8GB — exceeding a 1Gi container limit and causing OOMKill. UseContainerSupport makes the JVM read cgroup limits. Default since Java 8u191+."},
    {"level":2,"diff":2,"scenario":4,"q":"What is the difference between resources.requests.memory and resources.limits.memory for a JVM pod?","opts":["They are the same thing","Requests is the scheduling guarantee (Kubernetes ensures this much on the node); limits is the kill boundary (the kernel kills the process if it exceeds this)","Requests controls heap; limits controls non-heap","Requests is for startup; limits is for steady state","Limits is advisory; requests is enforced"],"ans":1,"fb":"Requests: used by the scheduler to place pods. Limits: enforced by the kernel — exceeding it causes SIGKILL. For JVM workloads, set requests close to limits (JVM reserves heap at startup), and set limits to accommodate heap + non-heap."},
    {"level":2,"diff":3,"scenario":4,"q":"A JVM pod has requests.memory=512Mi and limits.memory=1Gi. It consistently uses 800Mi. What is the risk?","opts":["No risk — it's within limits","The pod may be scheduled on a node without 800Mi available — the scheduler only guarantees 512Mi, and the pod could be evicted under node memory pressure","The pod will be OOM-killed at 512Mi","The JVM will crash at 512Mi","Kubernetes will autoscale the pod"],"ans":1,"fb":"The scheduler places based on requests (512Mi). If the node is overcommitted, Kubernetes may evict Burstable pods (requests != limits). For JVM workloads with predictable memory, setting requests = limits (Guaranteed QoS) prevents eviction."},

    {"level":3,"diff":1,"scenario":0,"q":"A Spring Boot service is using more memory than expected. Which components should you check first?","opts":["Only the heap size","HikariCP connection pool, Kafka consumer buffers, Tomcat thread pool, and Spring caches — the major memory consumers in a typical Spring Boot service","Only the number of REST endpoints","The JVM version","The container's CPU allocation"],"ans":1,"fb":"In a typical Spring Boot service: HikariCP holds DB connections (each ~1MB), Kafka consumers allocate fetch buffers (fetch.max.bytes per consumer, off-heap), Tomcat threads each have a ~1MB stack, and Spring caches can grow unboundedly."},
    {"level":3,"diff":2,"scenario":0,"q":"A service has spring.kafka.consumer.properties.fetch.max.bytes=52428800 (50MB) and spring.kafka.listener.concurrency=3. How much off-heap memory do the Kafka consumers use?","opts":["50MB total","150MB","300MB — Kafka double-buffers internally, so 3 x 50MB x 2","Zero — Kafka buffers are on the heap","It depends on partition count"],"ans":2,"fb":"Each Kafka consumer thread allocates direct byte buffers for fetching. With double-buffering (one being processed, next being filled): 3 x 50MB x 2 = 300MB of direct byte buffers — entirely outside the JVM heap."},
    {"level":3,"diff":3,"scenario":0,"q":"Three identical pods run the same service, but pod A uses 400MB, pod B uses 600MB, and pod C uses 900MB. Same configuration. What is the most likely cause?","opts":["Different JVM versions on different nodes","Different Kafka partition assignments — the pod with more partitions has more consumer buffers and cached data","Random GC timing","Different container limits","Network latency"],"ans":1,"fb":"Kafka partitions are assigned unevenly across consumers. A pod assigned more partitions uses more fetch buffer memory and may cache more per-partition state. Configuration is identical but runtime state diverges."},

    {"level":3,"diff":1,"scenario":1,"q":"Which Actuator metric tells you current heap usage?","opts":["/actuator/health","jvm.memory.used (with area=heap tag)","hikaricp.connections.active","process.cpu.usage","jvm.threads.live"],"ans":1,"fb":"The Micrometer metric jvm.memory.used with tag area=heap reports current heap usage. Query at /actuator/metrics/jvm.memory.used?tag=area:heap. Related: jvm.memory.max shows -Xmx, jvm.memory.committed shows reserved OS memory."},
    {"level":3,"diff":2,"scenario":1,"q":"jvm.memory.used{area=heap} is stable but jvm.buffer.memory.used is growing. What does this indicate?","opts":["A heap memory leak","Direct byte buffers (off-heap) are accumulating — commonly from NIO, Kafka, or Netty not releasing buffers","GC is not running","Actuator metrics are wrong","Metaspace is growing"],"ans":1,"fb":"jvm.buffer.memory.used tracks direct byte buffers — memory outside the heap via ByteBuffer.allocateDirect(). Growth while heap is stable indicates off-heap accumulation. This memory counts toward the container limit but not -Xmx."},
    {"level":3,"diff":3,"scenario":1,"q":"After a load test, hikaricp.connections.active stays at 10 (pool max) and never decreases. hikaricp.connections.pending is 45. What does this tell you?","opts":["The database is healthy","All 10 connections are checked out and not being returned (possible leak), while 45 threads are blocked waiting","The pool is too large","HikariCP is misconfigured","The load test is still running"],"ans":1,"fb":"Active=10 (pool max) with pending=45 means the pool is exhausted. 10 connections are held and 45 threads are queued. If this persists after load stops, it's a connection leak. Check with leakDetectionThreshold."},

    {"level":3,"diff":1,"scenario":2,"q":"A log shows OutOfMemoryError: Metaspace. What ran out?","opts":["The JVM heap","The area where class definitions and metadata are stored — too many classes loaded","The container's total memory","Thread stack space","Direct byte buffers"],"ans":1,"fb":"Metaspace stores class metadata. OutOfMemoryError: Metaspace means more classes were loaded than the configured (or default) Metaspace can hold. Common causes: dynamic class generation (CGLIB, reflection, SpEL)."},
    {"level":3,"diff":2,"scenario":2,"q":"A service throws OutOfMemoryError: unable to create native thread. Heap is 40% full. What is the cause?","opts":["The heap is too small","The OS cannot allocate memory for a new thread stack — either too many threads exist or remaining memory is insufficient for another ~1MB stack","GC is not collecting threads","The thread pool is misconfigured","Kafka is creating too many partitions"],"ans":1,"fb":"Each thread needs a stack (~1MB by default). 'Unable to create native thread' means the OS can't allocate more stack memory. With a 1Gi container, 600MB heap, 150MB Metaspace, and 200 existing threads (200MB), only ~50MB remains."},
    {"level":3,"diff":3,"scenario":2,"q":"OutOfMemoryError: Java heap space occurs during a batch job processing 500K records in a single @Transactional method. The same job worked for 100K records. What is the cause?","opts":["The heap is globally too small","Hibernate's first-level cache holds all 500K entities in memory for the duration of the transaction","The database query is too slow","Kafka is consuming too much memory","The GC algorithm is wrong for batch workloads"],"ans":1,"fb":"Hibernate's first-level (session) cache retains every entity loaded or persisted within a transaction. With 500K entities in a single @Transactional scope, all stay in heap until commit. Fix: flush() and clear() every 1000 records."},

    {"level":3,"diff":1,"scenario":3,"q":"When reviewing a PR, which of these patterns is a memory risk?","opts":["Using a List<String> as a local variable","Adding entries to a ConcurrentHashMap field based on request data with no size limit","Using Spring's @Autowired for dependency injection","Creating a new ObjectMapper in a utility method","Using Stream.of() for a small collection"],"ans":1,"fb":"A ConcurrentHashMap field that grows based on request data with no size limit is a classic memory leak. Every unique key adds an entry that is never removed. Fix: use a bounded cache (Caffeine with maximumSize) or add eviction."},
    {"level":3,"diff":2,"scenario":3,"q":"A PR adds @Cacheable('partnerRates') using Spring's default cache. The method returns exchange rates per partner per currency pair. What memory concern should you raise?","opts":["No concern — caching is good","Spring's default ConcurrentMapCacheManager has no size limit. Many partner x currency combinations will grow the cache indefinitely","The concern is only cache staleness, not memory","@Cacheable always uses off-heap","The concern is thread safety"],"ans":1,"fb":"With default Spring caching, every unique key becomes a permanent entry. 500 partners x 50 currencies = 25,000 entries. Recommend: configure Caffeine with maximumSize and expireAfterWrite."},
    {"level":3,"diff":3,"scenario":3,"q":"A PR introduces a new @Async thread pool with corePoolSize=50 and maxPoolSize=200. The service runs in a 1Gi container with -Xmx=600m. What memory concern should you raise?","opts":["No concern — thread pools are standard","200 threads at max x ~1MB stack each = 200MB. Combined with existing threads, heap, and Metaspace, total may exceed 1Gi under load","The concern is CPU, not memory","@Async pools don't create real threads","The concern is only pool exhaustion"],"ans":1,"fb":"Each thread consumes ~1MB stack memory outside the heap. Budget: 600MB heap + 150MB Metaspace + existing 100 threads (100MB) + new pool 200 threads (200MB) = ~1.05GB — exceeds 1Gi. Fix: reduce maxPoolSize, reduce -Xmx, or increase container limit."},

    {"level":3,"diff":1,"scenario":4,"q":"You need to estimate whether a new service fits within 1Gi. It has: -Xmx=500m, ~150 Tomcat threads, 5 Kafka consumers (30MB fetch buffer each), estimated Metaspace 100MB. Does it fit?","opts":["Yes — 500MB heap + 100MB Metaspace = 600MB","No — 500MB heap + 150 stacks (150MB) + 5 Kafka buffers x 30MB x 2 (300MB) + 100MB Metaspace + ~50MB overhead = ~1.1GB","Yes — non-heap is negligible","Impossible to estimate without running the service","Yes — Kubernetes allocates extra automatically"],"ans":1,"fb":"Memory budget: Heap 500MB + Stacks 150MB + Kafka buffers 300MB + Metaspace 100MB + overhead 50MB = ~1.1GB > 1Gi. Options: reduce -Xmx, reduce fetch.max.bytes, reduce Tomcat threads, or increase limit to 1.5Gi."},
    {"level":3,"diff":2,"scenario":4,"q":"A service currently uses 800MB total in a 1Gi container. A new feature adds 3 @Cacheable methods. How do you assess whether the service still fits?","opts":["Caches are negligible","Estimate cache sizes: number of unique keys x size per entry x 3 caches, then add to 800MB. If total exceeds 1Gi, increase limit or bound the caches","Just deploy and see","Add a heap dump to check","Increase -Xmx by the cache size"],"ans":1,"fb":"Cache memory is heap memory. Estimate: if each cache holds 10K entries at 500 bytes = ~5MB per cache, 15MB total — fine. But 100K entries at 50KB each = 500MB+ — not fine. Always calculate worst-case and configure bounded caches."},

    {"level":4,"diff":1,"scenario":0,"q":"Which tool takes a heap dump from a running JVM without restarting it?","opts":["jstack","jcmd <pid> GC.heap_dump <file>","jstat -gcutil","async-profiler","kubectl logs"],"ans":1,"fb":"jcmd <pid> GC.heap_dump <file> triggers a heap dump on a live JVM. It briefly pauses all threads. jstack produces thread dumps. jstat shows GC stats. async-profiler is for CPU/allocation sampling."},
    {"level":4,"diff":2,"scenario":0,"q":"In Eclipse MAT, a ConcurrentHashMap shows 'Retained Heap' of 800MB in a 1GB heap. What does 'retained heap' mean?","opts":["The map's own memory usage","The total memory that would be freed if this map were garbage collected — including everything it exclusively references","The maximum the map can grow to","Memory allocated but unused by the map","Memory used by keys only"],"ans":1,"fb":"Retained heap = memory freed if this object and all objects it exclusively retains were GC'd. 800MB retained means the map references an object graph totalling 800MB. The map's 'shallow heap' (structure itself) might be a few MB. Retained heap is the key metric for finding leaks in MAT."},
    {"level":4,"diff":3,"scenario":0,"q":"A heap dump shows 600MB of byte[] retained by a single LinkedHashMap with access-order enabled but no eviction. The service is multi-tenant. What is the diagnosis?","opts":["Normal serialisation buffers","An unbounded LRU-style cache accumulating entries per tenant without eviction","A Kafka consumer buffer","HikariCP connection state","A logging buffer"],"ans":1,"fb":"LinkedHashMap with access-order is an LRU cache, but without removeEldestEntry() returning true, entries accumulate forever. In multi-tenant service, each tenant's data adds permanently. Fix: switch to Caffeine with maximumSize and expireAfterWrite."},

    {"level":4,"diff":1,"scenario":1,"q":"In GC logs, a collection event shows 'before' and 'after' heap sizes nearly equal. What does this indicate?","opts":["GC ran efficiently","GC ran but reclaimed almost no memory — most objects survived, suggesting a potential leak or undersized heap","The heap is correctly sized","GC didn't run","The log format is wrong"],"ans":1,"fb":"If before ~= after, very few objects were collected — most are still reachable. Repeated pattern = strong leak signal or severely undersized heap. Healthy GC shows significant drops: before >> after."},
    {"level":4,"diff":2,"scenario":1,"q":"GC logs show frequent minor GCs with high allocation rate, but old-gen stays stable. Is this a problem?","opts":["Yes — frequent GC is always bad","No — high allocation of short-lived objects is normal under load. Stable old-gen means objects are collected in young gen. It's throughput, not a leak.","Yes — it's a memory leak","No — but only below 1GB/s","Yes — eden is too small"],"ans":1,"fb":"High allocation rate with stable old-gen = healthy high-throughput pattern. Short-lived objects created and collected in young gen. If old-gen were rising, that would indicate promotion and a leak signal."},
    {"level":4,"diff":3,"scenario":1,"q":"After a leak fix, GC logs show old-gen growth has slowed but not stopped. Over 24 hours, old-gen rises by 50MB. Is the fix complete?","opts":["Yes — slow growth is acceptable","No — a complete fix would produce stable old-gen baseline with sawtooth. Ongoing growth means retained objects still accumulating. Further profiling needed.","Yes — 50MB/day is normal","No — switch GC algorithms","Wait a week"],"ans":1,"fb":"A properly fixed service shows stable old-gen — rises and falls with GC around a baseline. 50MB/day x 30 days = 1.5GB — eventual crisis. Take two heap dumps 4 hours apart, compare in MAT."},

    {"level":4,"diff":1,"scenario":2,"q":"What does JFR offer for memory investigation that Grafana metrics do not?","opts":["JFR shows the same metrics in different format","JFR profiles allocation hotspots — which methods create the most objects — giving code-level detail","JFR fixes memory leaks","JFR only works on Oracle JDK","JFR replaces heap dumps"],"ans":1,"fb":"Grafana shows aggregates (total heap, GC pauses). JFR profiles at method level: which methods allocate the most, allocation rate per call site, object sizes, promotion behaviour. This traces GC pressure to specific code. Safe for production (<1% overhead)."},
    {"level":4,"diff":2,"scenario":2,"q":"A JFR recording shows the top allocator is byte[] from ch.qos.logback.classic.Logger at 300MB/s. What does this mean?","opts":["Logback has a memory leak","The service generates enormous log output, and string formatting allocates byte arrays at massive rate, increasing GC pressure","JFR miscounting","Logback needs upgrading","The bytes are from Kafka"],"ans":1,"fb":"Log message formatting creates temporary byte[] and String objects. At DEBUG level with high request volume, this produces hundreds of MB/s of garbage. Fix: set production logging to INFO, use parameterised logging (log.info('msg {}', var))."},
    {"level":4,"diff":3,"scenario":2,"q":"JFR shows TierEvaluationContext objects being promoted to old gen despite being short-lived. What explains this?","opts":["Objects are too large for young gen","The tier calculation spans multiple minor GC cycles — objects survive collections during processing and get promoted","Objects are static singletons","JFR misreporting","Old gen is undersized"],"ans":1,"fb":"Promotion happens when objects survive enough young gen collections. If calculation takes longer than minor GC interval, objects created at the start survive and get promoted. Fix: make calculations faster or increase young gen size."},

    {"level":4,"diff":1,"scenario":3,"q":"A thread dump shows 150 threads in TIMED_WAITING inside HikariPool.getConnection. What does this indicate?","opts":["Database is performing normally","The connection pool is exhausted — 150 threads are queued waiting for a connection","There is a deadlock","Too many threads","Kafka consumers are blocked"],"ans":1,"fb":"TIMED_WAITING inside HikariPool.getConnection means threads are waiting for a connection from the pool. 150 waiting = pool fully checked out. Cascades into HTTP timeouts. Root cause: leaked connections, slow queries, or undersized pool."},
    {"level":4,"diff":2,"scenario":3,"q":"A thread dump shows deadlock: Thread A holds lock X, waits for Y. Thread B holds lock Y, waits for X. Both in @Transactional methods. Most likely cause?","opts":["JVM bug","Two transactions acquiring database row locks in different orders","Spring proxy mechanism","Kafka consumer threads interfering","HikariCP internal deadlock"],"ans":1,"fb":"Classic lock-ordering deadlock at the database level. Thread A locks row X then needs Y; Thread B locked Y then needs X. Fix: consistent lock ordering (always lower ID first) or optimistic locking (@Version)."},
    {"level":4,"diff":3,"scenario":3,"q":"A thread dump shows 200 threads — 180 in RUNNABLE inside java.util.HashMap.put. What could cause this?","opts":["Normal HashMap usage","A non-thread-safe HashMap used concurrently — multiple threads cause infinite loop in bucket chains","Map is too large","GC interfering","HashCode is slow"],"ans":1,"fb":"HashMap is not thread-safe. Concurrent modification can form cycles in bucket chains. Threads get stuck in infinite loops inside put(), appearing RUNNABLE but burning CPU forever. Fix: use ConcurrentHashMap or synchronise access."},

    {"level":4,"diff":1,"scenario":4,"q":"A service's Metaspace usage grows slowly over weeks, long after startup. What is the most likely cause?","opts":["Normal class loading during every request","Dynamic class generation — CGLIB proxies, SpEL compilation, reflection-based serialisation creating new classes at runtime","JVM loading more classpath classes over time","Metaspace fragmentation","GC not running on Metaspace"],"ans":1,"fb":"After startup, classpath is fully loaded and Metaspace should plateau. Continued growth means runtime class creation. Common: CGLIB proxy regeneration, SpEL per unique expression, Groovy scripts creating classloaders."},
    {"level":4,"diff":2,"scenario":4,"q":"Metaspace grows 5MB/day. At this rate, the container will eventually be OOM-killed. What is the two-part fix?","opts":["Just increase container limit","Set -XX:MaxMetaspaceSize as safety net (e.g., 256m) AND investigate what generates classes at runtime","Just reduce -Xmx","Switch to ZGC","Restart the pod daily"],"ans":1,"fb":"Part 1: MaxMetaspaceSize converts silent OOMKill into visible OutOfMemoryError: Metaspace. Part 2: Use JFR class loading events or -verbose:class to find the source. Common fixes: disable DevTools in prod, cache compiled SpEL, switch serialisation libraries."},

    {"level":5,"diff":1,"scenario":0,"q":"A latency-sensitive service needs P99 under 30ms. G1GC produces occasional 100ms pauses. You evaluate ZGC. What is the key trade-off?","opts":["ZGC is slower in all cases","ZGC eliminates stop-the-world pauses (sub-ms) but uses more CPU and requires more memory (~2x RSS). P99 improves but CPU and memory cost increases.","ZGC only works on heaps above 16GB","ZGC is experimental","ZGC requires a different JVM"],"ans":1,"fb":"ZGC performs marking and compaction concurrently. Trade-offs: ~15-20% more CPU, coloured pointers increase RSS ~2x heap mapping. For P99 SLOs, ZGC is often right if the pod has enough CPU."},
    {"level":5,"diff":2,"scenario":0,"q":"After switching to ZGC, P99 drops from 100ms to 3ms. But the pod is OOM-killed because ZGC's RSS is 2x G1's. What is the fix?","opts":["Switch back to G1","Increase container memory limit to accommodate ZGC's higher RSS. The P99 improvement justifies the cost.","Reduce -Xmx by half","Switch to Shenandoah","Set ZGC SoftMaxHeapSize to half"],"ans":1,"fb":"ZGC's coloured pointers map heap multiple times, increasing RSS. Increase container limit accordingly. Reducing -Xmx defeats the purpose. SoftMaxHeapSize controls GC aggressiveness, not RSS."},

    {"level":5,"diff":1,"scenario":3,"q":"Multiple teams configure JVMs differently. One team has no GC logging, no HeapDumpOnOutOfMemoryError, and -Xmx at 95% of container limit. What is the risk?","opts":["No risk — each team knows best","No diagnostic data when memory issues occur, and -Xmx at 95% leaves almost no room for non-heap, making OOMKill likely under any load increase","Only slightly higher memory usage","Only a risk for the platform team","GC logging has too much overhead"],"ans":1,"fb":"Without GC logging, no visibility into allocation patterns. Without HeapDumpOnOutOfMemoryError, OOM crashes produce no evidence. With -Xmx at 95%, guaranteed OOMKill under load. Modern GC logging has negligible overhead."},
    {"level":5,"diff":2,"scenario":3,"q":"What should a mandatory JVM baseline include for all Spring Boot services?","opts":["Only -Xmx","UseContainerSupport, HeapDumpOnOutOfMemoryError with HeapDumpPath, GC logging (-Xlog:gc*), MaxMetaspaceSize as safety net, and -Xmx at 60-70% of container limit","Mandate ZGC for all services","Only Grafana dashboards","Weekly heap dumps from all services"],"ans":1,"fb":"A baseline ensures: container awareness, post-mortem capability, observability (GC logging), safety net for non-heap growth, and correct heap sizing. Delivered via shared Helm chart or ConfigMap template with per-service overrides."},

    {"level":5,"diff":1,"scenario":4,"q":"Your team evaluates upgrading from Java 17 to 21. What memory-related changes should you assess?","opts":["No memory changes between 17 and 21","ZGC generational mode (default in 21), virtual thread memory model, and potential GC ergonomics changes","Only virtual thread stack size","Only SecurityManager removal","Only the new GC performance"],"ans":1,"fb":"Java 21: generational ZGC (more efficient, default), virtual threads with different memory model (stacks on heap, not OS stacks), GC ergonomics changes. Test: existing -Xmx still works, virtual threads don't create heap pressure, libraries compatible with new threading."},

    {"level":6,"diff":1,"scenario":0,"q":"You're designing a fleet-wide memory reliability strategy. What should it include?","opts":["Just standardised -Xmx values","Standard JVM config, mandatory HeapDumpOnOutOfMemoryError, GC anomaly alerting, automated JFR on threshold breach, and fleet-wide per-service memory dashboards","Only Grafana dashboards","Only incident runbooks","Only automated restarts on high memory"],"ans":1,"fb":"Complete strategy: prevention (standard config), detection (anomaly alerting, growth trends), diagnosis (auto heap dump, triggered JFR), visibility (per-service dashboards, not averages). Shifts from reactive to proactive."},
    {"level":6,"diff":2,"scenario":0,"q":"Your fleet dashboard shows average JVM heap at 45% across 20 services. A stakeholder says 'memory is fine.' Why might this be misleading?","opts":["Averages are always accurate","The average hides outliers — one service at 95% with a growing leak is invisible when averaged with 19 at 40%. Show per-service MAX or P95 instead.","45% is indeed healthy","The dashboard measures wrong","Averages are fine with alerts"],"ans":1,"fb":"Fleet averages are dangerous. 19 healthy at 40% + 1 leaking at 95% = average 43%. Fix: per-service panels, MAX() as top indicator, alert on per-service P95 memory."},

    {"level":6,"diff":1,"scenario":1,"q":"How does GC behaviour translate into SLA latency commitments?","opts":["GC has no SLA impact","GC pauses directly add to P99 latency — a 100ms pause means any in-flight request experiences 100ms+ additional latency. Memory configuration must be validated against SLA targets.","Only heap size matters","SLAs should exclude GC","GC impact is too small"],"ans":1,"fb":"GC pauses are stop-the-world. If SLA promises P99 < 50ms but the service has 100ms pauses every 30s, ~3% of requests violate purely from GC. GC algorithm, heap sizing, and allocation rate optimisation are SLA engineering."},

    {"level":6,"diff":1,"scenario":2,"q":"When evaluating virtual threads (Java 21) for your Spring Boot services, what is the key memory implication?","opts":["Virtual threads use same memory as platform threads","Virtual threads have much smaller stacks (heap-allocated), enabling millions of tasks — but ThreadLocal-heavy libraries may leak memory per virtual thread","Virtual threads eliminate connection pools","Virtual threads reduce heap usage","Virtual threads are only for batch"],"ans":1,"fb":"Platform threads: ~1MB OS stack each. Virtual threads: tiny heap-allocated continuations. But: ThreadLocal per virtual thread can cause heap growth (millions of virtual threads x ThreadLocal copy). HikariCP, Spring Security use ThreadLocal extensively. Evaluation must include ThreadLocal audit."}
  ]
};
