var TRACK_JVM = {
  "id": "jvm",
  "label": "JVM Understanding",
  "icon": "jvm",
  "desc": "Spring Boot 3 on GKE with PostgreSQL on Cloud SQL and Kafka. Covers JVM internals, memory management, thread behaviour, and production diagnosis.",
  "levels": [
    {
      "num": 1, "name": "Foundations",
      "desc": "Reading what the application is telling you and understanding the basic runtime model.",
      "scenarios": [
        "Reading stack traces and understanding OOM/StackOverflow errors",
        "Using logs and Actuator endpoints for initial diagnosis",
        "Reading JVM dashboards in Grafana (heap, GC pauses)",
        "Understanding Pod restarts and probe configuration on GKE",
        "Understanding HikariCP connection pool basics"
      ]
    },
    {
      "num": 2, "name": "Practitioner",
      "desc": "Configuring the runtime correctly for your service and diagnosing the most common production problems.",
      "scenarios": [
        "Sizing JVM heap and GKE resource limits correctly",
        "Reading GC logs and distinguishing allocation surges from leaks",
        "Diagnosing Kafka consumer lag and tuning consumer config",
        "Using JFR for production investigation without downtime",
        "Writing reliable integration tests with Testcontainers"
      ]
    },
    {
      "num": 3, "name": "Advanced",
      "desc": "Diagnosing non-obvious production problems and tuning the runtime under real load.",
      "scenarios": [
        "Analysing heap dumps to find memory leaks and retained objects",
        "Reading thread dumps to diagnose stalls and lock contention",
        "Diagnosing Kafka consumer rebalancing and duplicate processing",
        "CPU profiling with async-profiler or JFR to find hot code paths",
        "Tracing HikariCP connection leaks under load"
      ]
    },
    {
      "num": 4, "name": "Specialist",
      "desc": "Owning JVM health across multiple services and solving platform-level performance problems.",
      "scenarios": [
        "Comparing GC algorithms (G1/ZGC/Shenandoah) under production load",
        "Investigating platform-level issues (CFS throttling, NUMA, noisy neighbours)",
        "Designing Kafka consumer scaling strategies for volume spikes",
        "Reducing JVM latency variance for SLO-sensitive services",
        "Diagnosing cross-service connection pool cascades"
      ]
    },
    {
      "num": 5, "name": "Expert",
      "desc": "Setting JVM and runtime standards across the organisation and mentoring teams through complex production issues.",
      "scenarios": [
        "Defining org-wide JVM baseline configurations for GKE Spring Boot services",
        "Owning production incident diagnosis and turning incidents into learning sessions",
        "Evaluating new Java versions and JVM distributions for the platform",
        "Designing realistic load tests that match production traffic patterns",
        "Defining observability standards for Spring Boot services (metrics, spans, SLOs)"
      ]
    },
    {
      "num": 6, "name": "Authority",
      "desc": "JVM platform strategy, tooling investment, and organisation-wide runtime governance.",
      "scenarios": [
        "Leading long-term JVM strategy decisions (LTS versions, GraalVM, container-native tuning)",
        "Building and adopting standardised JVM observability tooling across all services",
        "Owning complex cross-team production incident investigations",
        "Producing structured assessments for major platform shifts (e.g. Java 17→21)",
        "Identifying training gaps and building the JVM curriculum for the organisation"
      ]
    }
  ],
  "questions": [
    {"level":1,"diff":1,"scenario":0,"q":"A pod log shows `java.lang.OutOfMemoryError: Java heap space`. What does this mean?","opts":["The JVM ran out of native memory","The JVM heap has no free space to allocate a new object","The OS killed the process due to CPU overload","A stack overflow occurred during recursion","The container's filesystem is full"],"ans":1,"fb":"'Java heap space' means the garbage collector could not free enough heap memory to satisfy an allocation request. Native memory OOM has a different message. CPU overload does not produce this error. Stack overflow produces `StackOverflowError`, not `OutOfMemoryError`."},
    {"level":1,"diff":1,"scenario":0,"q":"A stack trace ends with `java.lang.StackOverflowError`. What is the most likely root cause?","opts":["The JVM heap is exhausted","A thread is stuck waiting on a lock","Infinite or deeply nested recursion","Too many threads were created","A null was dereferenced in a loop"],"ans":2,"fb":"StackOverflowError occurs when recursive method calls exhaust the thread's stack frames. Heap exhaustion produces OutOfMemoryError. Lock waits produce blocked thread state, not a stack overflow. Too many threads causes `OutOfMemoryError: unable to create native thread`."},
    {"level":1,"diff":2,"scenario":0,"q":"A stack trace shows `Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`. What does this indicate?","opts":["The heap is configured too large","The JVM spent >98% of time in GC but recovered <2% of heap","A memory leak in native (off-heap) code","The container memory limit was hit before the JVM limit","Metaspace is exhausted"],"ans":1,"fb":"'GC overhead limit exceeded' is thrown when the JVM detects it is spending almost all CPU time collecting garbage with negligible recovery — a strong signal of a heap memory leak or undersized heap. Metaspace exhaustion has its own message. Native memory issues show 'unable to allocate ... bytes'."},
    {"level":1,"diff":3,"scenario":0,"q":"A service throws `OutOfMemoryError: Java heap space` only on specific tenant requests, not on others. What is the most useful first hypothesis?","opts":["The heap is too small for all workloads","Those tenant requests trigger processing of much larger datasets or unbounded collections","The JVM version has a bug affecting those code paths","GC is not running on those threads","The container memory limit is misconfigured per tenant"],"ans":1,"fb":"OOM errors scoped to specific tenants strongly suggest those requests process data that grows unboundedly (e.g., loading all records into memory). Global heap sizing issues would affect all requests equally. JVM version bugs are possible but rare. GC runs across all threads — it is not per-tenant. Memory limits are pod-level, not per-tenant."},

    {"level":1,"diff":1,"scenario":1,"q":"Which Spring Boot Actuator endpoint shows whether the application is ready to serve traffic?","opts":["/actuator/metrics","/actuator/health/readiness","/actuator/info","/actuator/env","/actuator/loggers"],"ans":1,"fb":"The `/actuator/health/readiness` endpoint returns readiness state, which Kubernetes uses to decide whether to route traffic to a pod. `/health/liveness` indicates the process is alive. The other endpoints expose configuration, metrics, and logging — not readiness state."},
    {"level":1,"diff":1,"scenario":1,"q":"A Spring Boot service logs `ERROR` entries but the pod is still running. What Actuator endpoint helps you see if the app considers itself healthy?","opts":["/actuator/metrics","/actuator/health","/actuator/threaddump","/actuator/loggers","/actuator/conditions"],"ans":1,"fb":"`/actuator/health` aggregates health indicators (DB connectivity, disk space, custom checks) and returns UP/DOWN/DEGRADED. Errors in logs do not automatically flip health to DOWN — the health endpoint tells you the app's own assessment. Thread dump and metrics are diagnostic but do not report overall health state."},
    {"level":1,"diff":2,"scenario":1,"q":"You need to temporarily increase log verbosity for HikariCP to DEBUG without redeploying. Which Actuator endpoint enables this?","opts":["/actuator/env (POST)","/actuator/loggers/{name} (POST)","/actuator/refresh","/actuator/heapdump","/actuator/configprops"],"ans":1,"fb":"POSTing to `/actuator/loggers/com.zaxxer.hikari` with `{\"configuredLevel\":\"DEBUG\"}` changes the log level at runtime without restart. `/actuator/env` exposes properties but does not change log levels directly. `/actuator/refresh` reloads config but requires Spring Cloud Config. Heap dump and configprops are read-only diagnostics."},

    {"level":1,"diff":1,"scenario":2,"q":"In a Grafana JVM dashboard, 'Used Heap' climbs steadily over hours and never drops. What does this pattern suggest?","opts":["Normal JVM behaviour — heap grows until GC runs","A memory leak — objects are being retained and not collected","The heap is too small","GC is running too frequently","The service has high throughput temporarily"],"ans":1,"fb":"Steady heap growth without drops indicates GC is not reclaiming memory, suggesting objects are being retained (a memory leak). Normal GC behaviour produces a sawtooth pattern: heap rises then drops sharply after a collection. Frequent GC would appear as rapid oscillations, not a flat climb."},
    {"level":1,"diff":2,"scenario":2,"q":"A Grafana panel shows 'GC Pause Duration' spiking to 500ms every few minutes on a G1GC service. What is the immediate concern?","opts":["This is normal — G1 always pauses for 500ms","Application threads are stopped for 500ms, causing latency spikes","The JVM is about to crash","Metaspace is being resized","GC logs are misconfigured"],"ans":1,"fb":"GC pause events stop all application threads (stop-the-world). A 500ms pause every few minutes will directly cause P99/P999 latency spikes visible to callers. G1GC is designed to keep pauses under 200ms by default. This pattern warrants heap sizing review and GC tuning."},
    {"level":1,"diff":3,"scenario":2,"q":"'Non-Heap Used' (Metaspace) grows slowly over days and never decreases. What is the most likely cause in a Spring Boot service?","opts":["A heap memory leak","Dynamic class loading (e.g., reflection, CGLIB proxies, Groovy scripts) creating new classes without unloading old ones","Normal class loading during startup","GC not running on Metaspace","A JVM bug in Spring Boot 3"],"ans":1,"fb":"Metaspace grows when new classes are loaded and shrinks only when classloaders are GC'd. Steady growth in production (after startup plateau) suggests dynamic class generation — common with CGLIB proxies, reflection-heavy code, or scripting engines that create new classloaders repeatedly. Startup-only growth would plateau quickly and not continue for days."}  ,

    {"level":1,"diff":1,"scenario":3,"q":"A GKE pod is restarting repeatedly with exit code 137. What caused it?","opts":["The liveness probe failed","The JVM threw an unhandled exception","The container was OOM-killed by the Linux kernel","The pod exceeded its CPU limit","The readiness probe failed"],"ans":2,"fb":"Exit code 137 means the process was killed by signal 9 (SIGKILL), which the Linux OOM killer sends when the container exceeds its memory limit. Liveness probe failures cause a restart but with a different event in `kubectl describe`. Readiness failures remove the pod from service endpoints but do not restart it. CPU throttling does not kill the pod."},
    {"level":1,"diff":1,"scenario":3,"q":"What is the difference between a liveness probe and a readiness probe in GKE?","opts":["Liveness restarts the pod if it fails; readiness removes it from load balancer endpoints if it fails","Readiness restarts the pod; liveness removes it from the load balancer","Both restart the pod — liveness is for startup, readiness is for steady state","Liveness controls traffic routing; readiness controls pod scheduling","They are identical — the names are interchangeable"],"ans":0,"fb":"Liveness: if the check fails, Kubernetes kills and restarts the pod. Readiness: if the check fails, the pod is removed from the Service's endpoint list (no traffic) but not restarted. This distinction matters — a database being temporarily unavailable should flip readiness, not liveness, to avoid unnecessary pod churn."},
    {"level":1,"diff":2,"scenario":3,"q":"A Spring Boot pod's liveness probe hits `/actuator/health` and the pod restarts every 10 minutes. What is the risk of this setup?","opts":["No risk — Actuator health is the correct endpoint for liveness","The health endpoint checks downstream dependencies; a DB blip will restart the pod unnecessarily","The endpoint is too slow for a probe","Liveness probes should use TCP socket checks, never HTTP","The probe will interfere with application traffic"],"ans":1,"fb":"Using the aggregate `/actuator/health` for liveness is dangerous because it includes downstream dependency checks (database, Kafka, etc.). A transient DB hiccup will flip health to DOWN, causing Kubernetes to kill the pod — which makes the outage worse. Best practice: use `/actuator/health/liveness` for liveness (process-only checks) and `/actuator/health/readiness` for readiness."},

    {"level":1,"diff":1,"scenario":4,"q":"What does HikariCP's `maximumPoolSize` control?","opts":["The maximum number of threads the service can spawn","The maximum number of database connections the pool will open","The maximum time a query can run before being killed","The maximum number of concurrent HTTP requests","The maximum size of the result set returned from a query"],"ans":1,"fb":"`maximumPoolSize` is the upper bound on physical database connections HikariCP will open. Exceeding this causes threads to wait for a connection. It is unrelated to application threads, query timeouts, HTTP concurrency, or result set sizes."},
    {"level":1,"diff":2,"scenario":4,"q":"A service logs `HikariPool-1 - Connection is not available, request timed out after 30000ms`. What is the most likely cause?","opts":["The database is down","All pool connections are in use and none were returned within the timeout","The JDBC driver version is incompatible","The pool was never initialised","Network latency is too high"],"ans":1,"fb":"This message means the pool is exhausted — all `maximumPoolSize` connections are checked out and no thread returned one within `connectionTimeout`. Common causes: slow queries holding connections, connection leaks (connections checked out but never returned), or pool sized too small for the load. A full DB outage would show a different error (connection refused/reset)."},
    {"level":1,"diff":3,"scenario":4,"q":"A service has `maximumPoolSize=10` and `minimumIdle=10`. GKE scales it to 8 replicas. How many database connections could this service hold open at peak?","opts":["10","18","80","100","20"],"ans":2,"fb":"Each pod maintains up to `maximumPoolSize` connections independently. With 8 replicas and a pool size of 10, the total is 8 × 10 = 80 connections. Cloud SQL has per-instance connection limits (typically 100–4000 depending on tier), so horizontal scaling multiplies connection pressure. This is why `maximumPoolSize` must account for expected replica count."}  ,

    {"level":2,"diff":1,"scenario":0,"q":"In a GKE pod spec, what happens if JVM heap (`-Xmx`) is set larger than the container's memory limit?","opts":["The JVM silently caps heap at the container limit","The pod is OOM-killed when heap usage approaches the limit","Kubernetes rejects the deployment","The JVM uses swap space instead","The pod is evicted during scheduling"],"ans":1,"fb":"The container memory limit is enforced by the Linux kernel via cgroups. If the JVM tries to use more memory (heap + non-heap + native) than the limit, the kernel sends SIGKILL (exit code 137). The JVM does not know about cgroup limits unless you use `-XX:+UseContainerSupport` (default in Java 8u191+/Java 11+). Setting -Xmx above the limit leaves no headroom for non-heap memory."},
    {"level":2,"diff":2,"scenario":0,"q":"A Spring Boot service runs with `-Xmx512m` in a 768Mi memory-limit container. It is OOM-killed under load. What is the most likely reason?","opts":["512m heap is too small — increase it to 768m","Non-heap memory (Metaspace, threads, compiled code) consumes the remaining headroom, leaving none for the kernel","The readiness probe is misconfigured","HikariCP is consuming heap","The JVM version does not support container limits"],"ans":1,"fb":"Total JVM memory = heap + Metaspace + thread stacks + JIT code cache + off-heap buffers. Setting -Xmx to 512m in a 768Mi container leaves only 256Mi for all non-heap. Under load, thread count increases, JIT compiles more code, and Metaspace grows — all eating into that 256Mi. A common rule of thumb is to set -Xmx to 50–75% of the container limit."},
    {"level":2,"diff":3,"scenario":0,"q":"You are setting resource limits for a new Spring Boot service. What information do you need before choosing `requests.memory` and `limits.memory`?","opts":["Only the expected heap size (-Xmx)","Heap size, Metaspace size, thread count, off-heap buffers, and expected load profile","Only the heap size and the number of replicas","The database connection pool size only","The number of Kafka topics the service consumes"],"ans":1,"fb":"Container memory must cover all JVM memory regions: heap, Metaspace, JIT code cache, thread stacks (each ~1MB), plus direct/off-heap buffers (Netty, Kafka client). Sizing based on heap alone is the most common cause of OOM kills. Replica count affects total cluster resource consumption but not per-pod sizing. Pool size and Kafka topics affect behaviour but the memory impact is small compared to heap/Metaspace."},

    {"level":2,"diff":1,"scenario":1,"q":"In GC logs, what does a GC event where 'before' and 'after' heap sizes are nearly equal indicate?","opts":["GC ran efficiently and reclaimed a lot of memory","GC ran but could not reclaim much memory — a potential memory leak","The heap is appropriately sized","GC did not run at all","The JVM is about to promote objects to old gen"],"ans":1,"fb":"In a typical GC log line, you see `before->after (total)`. If before and after are nearly equal, GC collected very little, meaning most live objects survived. This repeated pattern suggests either a memory leak (objects accumulating in old gen) or a heap that is nearly full. Efficient GC would show a significant drop from before to after."},
    {"level":2,"diff":2,"scenario":1,"q":"GC logs show frequent minor GCs with large allocation rates but stable heap after each collection. What does this indicate compared to a scenario with rising old-gen?","opts":["Both patterns are identical — minor GC frequency is always a problem","High allocation rate with stable heap after GC is a throughput issue, not a leak; rising old-gen suggests objects surviving to tenured generation","The JVM needs a larger eden space in both cases","Both indicate memory leaks","High allocation rate means the service is healthy"],"ans":1,"fb":"High allocation rate (many short-lived objects) increases minor GC frequency but if old-gen stays stable, objects are not being promoted — the sawtooth pattern is healthy under load. Rising old-gen means objects are surviving minor GCs and accumulating in tenured space, which is the early signal of a memory leak. These two patterns need different responses."},
    {"level":2,"diff":3,"scenario":1,"q":"After a memory leak fix, GC logs still show old-gen growing over 24 hours, but much slower than before. What is the correct interpretation?","opts":["The fix worked completely — old-gen growth is now expected","The fix partially reduced retained objects but did not fully resolve the leak; further profiling is needed","The JVM is warming up — wait longer before concluding","Old-gen growth is always normal and does not need investigation","The GC algorithm should be changed to ZGC"],"ans":1,"fb":"Reduced growth rate is a positive signal, but ongoing old-gen growth still indicates retained objects. A complete fix should produce a stable old-gen baseline (sawtooth pattern, not a slope). Acting as if the fix is complete (A) risks missing a remaining leak path. Blaming warmup after 24 hours (C) is not credible. Switching GC algorithms (E) does not fix leaks."},

    {"level":2,"diff":1,"scenario":2,"q":"A Kafka consumer group shows increasing lag on a topic. What does consumer lag mean?","opts":["The consumer is processing messages too fast","The offset committed by the consumer is behind the latest offset produced","The topic has too many partitions","The consumer is reconnecting frequently","The broker is overloaded"],"ans":1,"fb":"Consumer lag = latest offset (produced) minus committed offset (consumed). Growing lag means the consumer is falling behind the producer. It does not indicate the consumer is too fast — that would reduce lag. Partition count affects throughput but lag measures offset difference. Broker overload is possible but lag is a consumer-side metric."},
    {"level":2,"diff":2,"scenario":2,"q":"A Kafka consumer is lagging. You increase `max.poll.records` from 500 to 2000. Under what condition does this make things worse?","opts":["It always makes things worse — lower is better","If the consumer's processing time per batch exceeds `max.poll.interval.ms`, the consumer will be kicked out of the group","If the topic has fewer than 2000 messages","If the consumer group has only one member","If auto-commit is disabled"],"ans":1,"fb":"Increasing `max.poll.records` increases the batch size, which increases time-to-process per poll. If the total processing time exceeds `max.poll.interval.ms` (default 5 minutes), the broker assumes the consumer is dead and triggers a rebalance, making lag worse. The fix is either to reduce processing time per batch, increase `max.poll.interval.ms`, or process records concurrently."},
    {"level":2,"diff":3,"scenario":2,"q":"A service has one Kafka consumer thread and 12 partitions. Lag is growing. Adding replicas does not reduce lag. Why?","opts":["Kafka does not support horizontal scaling","Each partition can only be consumed by one consumer in the same group — if there is one consumer thread per pod, additional pods consume different partitions but a single-threaded pod cannot parallelize within its assigned partitions","Lag cannot be reduced by adding replicas","The consumer group must be restarted after scaling","The topic needs more partitions before scaling helps"],"ans":1,"fb":"Each partition is assigned to one consumer in a group. With 12 partitions and N pods (each with 1 thread), you get up to 12 effective parallel consumers. But if a single pod with 1 thread is slow at processing its assigned partitions, adding more pods shifts partitions around but each pod is still single-threaded per assigned partition. The fix is increasing consumer thread count per pod or increasing partitions if all pods are saturated."},

    {"level":2,"diff":1,"scenario":3,"q":"What is Java Flight Recorder (JFR) and why is it safe for production use?","opts":["A JVM debugger that pauses the application to collect data","A low-overhead continuous profiler built into the JVM that uses ring buffers and has < 1% overhead","A tool that requires a heap dump, which pauses all threads","An external agent that instruments bytecode at startup only","A GC log parser"],"ans":1,"fb":"JFR is a production-grade profiling and diagnostics tool built into the JVM (OpenJDK since Java 11, Oracle JDK since Java 7). It uses ring buffers and kernel-level event sampling, giving < 1% overhead. It does not pause threads (unlike heap dumps), does not require restart (unlike most profilers), and can be started/stopped on a live JVM with `jcmd`."},
    {"level":2,"diff":2,"scenario":3,"q":"You want to start a JFR recording on a running Spring Boot pod without restart. Which tool do you use?","opts":["jstack","jmap -histo","jcmd <pid> JFR.start","Attach VisualVM via remote JMX in production","Restart the pod with -XX:+FlightRecorder flag"],"ans":2,"fb":"`jcmd <pid> JFR.start` initiates a recording on a running JVM. `jstack` produces thread dumps. `jmap -histo` shows heap histogram (pauses the JVM briefly). Attaching VisualVM via JMX in production requires open JMX ports and is typically blocked. The `-XX:+FlightRecorder` flag is for older JDKs; on Java 11+ JFR is always available."},
    {"level":2,"diff":3,"scenario":3,"q":"A JFR recording from production shows hot allocations in a loop, but the service is live. How do you minimise impact while still getting useful data?","opts":["Take a heap dump instead — it is faster","Run a short JFR recording (e.g., 30–60 seconds) with the `profile` template, which is tuned for low overhead event selection","Use `jmap -histo:live` to force a full GC first","Restart the pod with verbose GC flags","Disable GC during the recording to reduce noise"],"ans":1,"fb":"A short timed recording with the built-in `profile` template is specifically designed for production use — it enables allocation profiling, GC events, and method sampling at low overhead. Heap dumps cause a full GC and freeze all threads. `jmap -histo:live` also triggers a full GC. Restarting loses the live state. Disabling GC is not a valid JVM option."},

    {"level":2,"diff":1,"scenario":4,"q":"What is the purpose of Testcontainers in integration tests?","opts":["To run tests in a Kubernetes cluster","To spin up real Docker containers (e.g., PostgreSQL, Kafka) for tests, then tear them down","To mock database calls without a real database","To run tests in parallel across multiple JVMs","To generate test data for load testing"],"ans":1,"fb":"Testcontainers starts real Docker containers for the duration of a test suite and stops them afterwards. This gives tests a real database, Kafka broker, or other dependency — not a mock — making tests more reliable and closer to production behaviour. It is not Kubernetes-based and does not mock; it runs actual services."},
    {"level":2,"diff":2,"scenario":4,"q":"A Testcontainers-based test is flaky — it passes locally but fails in CI with connection timeouts. What is the most common cause?","opts":["Testcontainers is not supported in CI","The test does not wait for the container to be ready before making connections","The Docker image is corrupted","The test uses too much memory","CI lacks internet access"],"ans":1,"fb":"The most common cause of Testcontainers flakiness in CI is racing against container startup. The container starts but the service inside is not yet ready to accept connections. Fix: use `waitingFor(Wait.forListeningPort())` or `Wait.forHealthcheck()` on the container definition. Docker image issues would fail consistently, not flakily."},
    {"level":2,"diff":3,"scenario":4,"q":"A service uses Liquibase migrations. In Testcontainers tests, migrations sometimes fail with table-already-exists errors. What is the root cause?","opts":["Testcontainers does not support Liquibase","The container is being shared across test classes without resetting state between tests","Liquibase is incompatible with the test PostgreSQL version","The JDBC URL is misconfigured","Each test creates a new schema but forgets to drop it"],"ans":1,"fb":"When multiple test classes share the same Testcontainers instance (via a static field or shared configuration), schema state from one class leaks into another. If one class runs migrations and a second class tries to run the same migrations, Liquibase sees existing tables and may error. Fixes: use `@DirtiesContext`, use per-test container instances, or configure Liquibase to skip on existing schema."},

    {"level":3,"diff":1,"scenario":0,"q":"Which tool produces a heap dump from a running JVM without restarting it?","opts":["jstack","jcmd <pid> GC.heap_dump <file>","jstat -gcutil","jmap -heap","async-profiler"],"ans":1,"fb":"`jcmd <pid> GC.heap_dump <file>` triggers a heap dump on a live JVM. `jcmd` is the recommended modern replacement for `jmap`. Both `jcmd` and `jmap -dump` work, but jcmd is preferred. `jstack` produces thread dumps. `jstat` shows live GC stats but not a dump. Note: heap dumps do pause all threads briefly."},
    {"level":3,"diff":2,"scenario":0,"q":"In a heap dump analysed with Eclipse MAT, the 'Retained Heap' of a single `ConcurrentHashMap` is 800MB out of 1GB total heap. What does this mean?","opts":["The map itself uses 800MB of direct memory","If the map were GC'd, 800MB of heap would be freed — it is retaining an object graph that large","The map has 800MB of key objects only","MAT is reporting incorrect data","The map is a soft reference and will be collected under memory pressure"],"ans":1,"fb":"Retained heap = the total memory that would be freed if this object (and everything it exclusively references) were garbage collected. An 800MB retained heap on a single map means the map holds references to a massive object graph. This is the key metric for finding memory leaks in MAT. Shallow heap (the map structure itself) would be tiny. Soft references are collected under pressure but this is a strong reference."},
    {"level":3,"diff":3,"scenario":0,"q":"A heap dump shows many `byte[]` instances totalling 600MB, all referenced by a `LinkedHashMap` set to access-order with no eviction. In a multi-tenant service, what does this indicate?","opts":["Normal byte array usage for image processing","A deliberately sized cache that is working correctly","An unbounded LRU-style cache that grows per-tenant request without eviction, retaining response data indefinitely","A Kafka consumer buffer that is too large","HikariCP storing connection state in byte arrays"],"ans":2,"fb":"A `LinkedHashMap` in access-order is commonly used as an LRU cache, but without a size limit (`removeEldestEntry` never returning true), it accumulates entries forever. In a multi-tenant service, each tenant's data adds to this map. The retained `byte[]` (likely serialised responses or query results) is the evidence. The fix: bound the cache or switch to a proper cache implementation like Caffeine with eviction policy."},

    {"level":3,"diff":1,"scenario":1,"q":"What does a thread dump show that a heap dump does not?","opts":["Object allocation sizes","Which threads are running, blocked, or waiting, and their current stack traces","Total heap usage","GC pause history","Class loading events"],"ans":1,"fb":"A thread dump is a snapshot of every thread's state (RUNNABLE, BLOCKED, WAITING, TIMED_WAITING) and its current stack trace. Heap dumps show object graphs and memory. Thread dumps are used to diagnose deadlocks, thread starvation, and lock contention. GC history is in GC logs. Class loading is in JFR events."},
    {"level":3,"diff":2,"scenario":1,"q":"A thread dump shows 20 threads in BLOCKED state, all waiting on `java.lang.Object.wait` inside `HikariPool.getConnection`. What is the diagnosis?","opts":["The database is down","The connection pool is exhausted — threads are waiting for a connection to become available","There is a deadlock between threads","The JVM has too many threads","Network I/O is blocking the threads"],"ans":1,"fb":"BLOCKED/WAITING inside `HikariPool.getConnection` is the classic pool exhaustion signature. Threads have called `getConnection()` and are queued waiting for a connection to be returned. This is different from a DB outage (which would show connection errors, not blocking). A deadlock would show two threads each holding a lock the other needs — a different pattern."},
    {"level":3,"diff":3,"scenario":1,"q":"A thread dump shows a deadlock: Thread A holds lock X and waits for lock Y; Thread B holds lock Y and waits for lock X. Both locks are on `@Transactional` service beans. What is the most likely root cause in Spring?","opts":["Spring does not support concurrent transactions","Two transactions are acquiring row-level database locks in different orders across service calls","The JVM has a bug with synchronized blocks","Both threads are waiting on the same Kafka partition","Spring's proxy-based AOP is creating duplicate beans"],"ans":1,"fb":"Deadlocks on transactional beans typically arise from acquiring database row locks in inconsistent order across transactions. Thread A locks row X then tries to lock row Y; Thread B has the opposite order. This is a distributed lock ordering problem, not a JVM bug. Spring AOP creates proxies but the deadlock pattern described (two locks, two threads, circular wait) points to lock ordering in the DB layer."},

    {"level":3,"diff":1,"scenario":2,"q":"What triggers a Kafka consumer group rebalance?","opts":["A new message is produced to the topic","A consumer joins or leaves the group, or a consumer fails to poll within `max.poll.interval.ms`","The Kafka broker is restarted","The consumer commits its offset","A new topic is created"],"ans":1,"fb":"Rebalances are triggered when the group membership changes (consumer joins/leaves/crashes) or when a consumer fails to call `poll()` within `max.poll.interval.ms`, causing the broker to consider it dead. Message production does not trigger rebalances. Offset commits and broker restarts may cause brief interruptions but the membership event is what initiates a rebalance."},
    {"level":3,"diff":2,"scenario":2,"q":"After a rebalance, a Kafka consumer processes a message it already processed before the rebalance. What caused this duplicate?","opts":["The message was published twice by the producer","The consumer committed its offset before the rebalance but the new consumer read from an earlier checkpoint","The consumer did not commit its offset before the rebalance completed, so it re-reads from the last committed offset","Kafka delivered the message to two consumers simultaneously","The `auto.offset.reset` was set to `earliest`"],"ans":2,"fb":"If a consumer processes messages but has not yet committed the offset when a rebalance happens, the partition is reassigned (possibly to the same consumer) and reading resumes from the last committed offset — causing reprocessing. This is the fundamental at-least-once delivery guarantee in Kafka. The fix is idempotent consumers or transactional processing."},
    {"level":3,"diff":3,"scenario":2,"q":"A consumer group experiences repeated rebalances. Logs show `WARN ... Commit cannot be completed since the group has already rebalanced`. What is the most effective fix?","opts":["Increase `max.poll.records` to reduce rebalance frequency","Decrease `max.poll.interval.ms` so rebalances complete faster","Reduce processing time per batch so it fits within `max.poll.interval.ms`, or increase `max.poll.interval.ms` to match actual processing time","Switch to manual offset management","Use a separate consumer group for each partition"],"ans":2,"fb":"'Commit cannot be completed' means the consumer took too long between polls, the broker declared it dead, triggered a rebalance, and the subsequent commit was rejected. Fix: either make processing faster (reduce work per poll batch) or increase `max.poll.interval.ms` to match actual processing duration. Decreasing `max.poll.interval.ms` makes it worse — less time to finish. Increasing `max.poll.records` increases batch size, worsening the problem."},

    {"level":3,"diff":1,"scenario":3,"q":"What does async-profiler measure that JFR method sampling alone does not capture well?","opts":["Memory leak detection","Off-CPU time — time threads spend blocked or waiting, not just on-CPU time","Kafka consumer lag","Database query execution plans","HTTP request latency"],"ans":1,"fb":"async-profiler uses OS-level signals (AsyncGetCallTrace + perf_events) to sample threads regardless of their state — including off-CPU time when threads are blocked on I/O, locks, or sleeping. Standard JFR method sampling only captures threads that are on-CPU (RUNNABLE). Off-CPU profiling is essential for diagnosing latency caused by lock contention or I/O waits."},
    {"level":3,"diff":2,"scenario":3,"q":"A CPU flame graph from async-profiler shows a wide block for `java.io.ObjectInputStream.readObject` taking 30% of CPU. What does this indicate?","opts":["The service is deserialising Java serialised objects at high frequency, which is expensive","The service is reading too many files from disk","Network I/O is the bottleneck","The JVM is spending time on garbage collection","Kafka message serialisation is the bottleneck"],"ans":0,"fb":"Java object serialisation/deserialisation is notoriously slow and CPU-intensive. A wide block in `ObjectInputStream.readObject` in a flame graph means a hot code path is frequently deserialising Java-serialised objects. Common culprits: HTTP session serialisation, caching layers using Java serialisation, or old integration points. The fix is switching to a faster serialisation format (Protobuf, JSON, Kryo)."},
    {"level":3,"diff":3,"scenario":3,"q":"A flame graph shows most CPU time in GC threads, not application threads. What should you investigate first before changing GC settings?","opts":["Switch to ZGC immediately","Increase heap size and check if allocation rate is pathologically high due to object-creation patterns in hot paths","Reduce the number of application threads","Disable JIT compilation","Add more CPU resources to the pod"],"ans":1,"fb":"High GC CPU typically means either the heap is too small (GC runs constantly) or the allocation rate is extremely high (many short-lived objects created in hot paths). Before tuning GC, identify what is allocating so heavily using JFR allocation profiling or MAT. Switching algorithms without addressing root cause just shifts the symptom. More CPU helps GC threads but does not reduce allocation rate."},

    {"level":3,"diff":1,"scenario":4,"q":"A HikariCP connection leak means a thread checked out a connection but never returned it. What HikariCP property helps detect this?","opts":["connectionTimeout","maximumPoolSize","leakDetectionThreshold","idleTimeout","keepaliveTime"],"ans":2,"fb":"`leakDetectionThreshold` (in milliseconds) causes HikariCP to log a warning with a stack trace if a connection is held longer than the threshold. This helps identify where in code a connection was checked out but not returned. It does not fix the leak but pinpoints it. `connectionTimeout` controls how long to wait for a connection. `idleTimeout` evicts idle connections."},
    {"level":3,"diff":2,"scenario":4,"q":"After enabling `leakDetectionThreshold=5000`, logs show the same stack trace — a method in a `@Scheduled` task — holding a connection for 30 seconds. What is the likely cause?","opts":["The task is running on a connection pool thread","The task opens a transaction (e.g., via `@Transactional`) but then performs slow external I/O or computation before the transaction closes, holding the connection","HikariCP is misconfigured","The scheduler thread pool is too small","The database query in the task is the slow part — this is expected"],"ans":1,"fb":"If a `@Scheduled` method is annotated `@Transactional`, Spring opens a transaction (and checks out a connection) at the start of the method. If the method then performs network calls, file I/O, or other slow work before returning, the connection is held for the entire duration. Fix: move non-DB work outside the transaction boundary, or restructure to minimise connection hold time."},
    {"level":3,"diff":3,"scenario":4,"q":"Connection leak warnings appear only during peak load, not during normal operation. What does this suggest about the leak?","opts":["The leak is worse under high thread contention — many threads requesting connections causes a race that leaves connections unclosed","Connections are returned slowly during high load due to contention, but the threshold is set too low — not a real leak","The database server is rejecting connections at peak load","HikariCP's leak detection does not work under load","The connection pool is too small"],"ans":0,"fb":"Load-correlated leaks often indicate code paths only exercised under concurrency: exception paths that skip `connection.close()`, async branches that abandon connections, or transactions left open in error handlers. Under low load, the same paths are hit rarely and leak detection threshold is not crossed. Under high load, many concurrent executions hit the path simultaneously and leaks accumulate. This warrants reviewing error handling in the stack traces provided by leakDetectionThreshold."},

    {"level":4,"diff":1,"scenario":0,"q":"What is the key design difference between G1GC and ZGC regarding stop-the-world pauses?","opts":["G1 has no stop-the-world pauses; ZGC does","G1 uses stop-the-world for major collections; ZGC performs concurrent marking and compaction, keeping pauses under 1ms regardless of heap size","Both have identical pause characteristics","ZGC is only for small heaps; G1 is for large heaps","G1 is faster on single-core; ZGC is faster on multi-core"],"ans":1,"fb":"G1GC aims to meet a configurable pause target but still has stop-the-world phases for full GCs and mixed collections. ZGC performs marking, relocation, and compaction concurrently with application threads, achieving sub-millisecond pauses even on multi-terabyte heaps. The trade-off: ZGC uses more CPU for concurrent work. G1 is a better default for throughput-oriented workloads; ZGC for latency-sensitive services."},
    {"level":4,"diff":2,"scenario":0,"q":"A latency-sensitive service (P99 SLO = 50ms) is running G1GC and hitting occasional 200ms GC pauses. You consider switching to ZGC. What is the main trade-off?","opts":["ZGC is slower overall — do not switch","ZGC eliminates long pauses but uses more CPU for concurrent GC work, which may reduce throughput and increase CPU resource costs","ZGC is only available on Java 17+","ZGC requires a larger heap — double your current allocation","ZGC does not support Spring Boot"],"ans":1,"fb":"ZGC's concurrent approach eliminates stop-the-world latency but the GC threads compete with application threads for CPU. On CPU-constrained pods (e.g., 1 vCPU), ZGC's background threads can reduce application throughput. On CPU-generous pods, ZGC's latency benefits usually justify the switch. Available since Java 11 (experimental), production-ready from Java 15. No Spring Boot compatibility issues."},
    {"level":4,"diff":3,"scenario":0,"q":"After switching a service from G1GC to ZGC, P99 latency improves but P50 latency degrades slightly and CPU utilisation increases 15%. The SLO team is satisfied. Should you roll back?","opts":["Yes — any throughput regression is unacceptable","No — P99 SLO is met, the CPU increase is the expected cost of ZGC's concurrent work, and P50 degradation is within acceptable range","Yes — CPU increase of 15% means the service will OOM","No — but switch to Shenandoah instead as it uses less CPU","Roll back only if a cost review flags the CPU increase"],"ans":1,"fb":"This is the expected ZGC trade-off: better tail latency, slightly more CPU, marginal throughput change. If the SLO is P99-based and is now met, the trade-off is valid. Rolling back because of P50 micro-regression when P99 (the SLO target) improved is the wrong call. A 15% CPU increase should be budgeted and monitored, not used as an automatic rollback trigger unless costs are prohibitive."},

    {"level":4,"diff":1,"scenario":1,"q":"What is CFS (Completely Fair Scheduler) CPU throttling in the context of GKE pods?","opts":["Kubernetes evicting a pod due to high memory usage","The Linux kernel limiting CPU usage of a container to its `cpu.limits` quota, pausing the process when the quota is exhausted within a scheduling period","A JVM feature that slows down threads during GC","GCP billing enforcement on CPU usage","A Kubernetes node autoscaler action"],"ans":1,"fb":"CFS throttling occurs when a container's CPU usage within a scheduling period (default 100ms) exceeds its configured CPU limit (cpu quota). The kernel pauses all container processes until the next period. This appears as application latency spikes without any GC or application-level cause — threads are simply frozen. Detectable via container CPU throttling metrics in GKE/Cloud Monitoring."},
    {"level":4,"diff":2,"scenario":1,"q":"A JVM service shows periodic latency spikes that correlate with CPU throttling metrics in GKE. GC logs are clean. What is the correct fix?","opts":["Increase JVM heap — throttling is caused by GC","Increase the pod's `cpu.limits` or remove CPU limits entirely to allow the pod to burst, while keeping `cpu.requests` accurate for scheduling","Switch from G1GC to ZGC","Add more replicas to distribute load","Reduce `max.poll.records` in Kafka"],"ans":1,"fb":"CFS throttling is a CPU limits problem, not a GC or heap problem. The fix is to raise CPU limits so the pod has quota headroom to handle bursts, or remove CPU limits and rely on requests for scheduling. Increasing heap does not affect CPU throttling. ZGC uses more CPU, which may worsen throttling. Adding replicas helps if the service is CPU-saturated overall but does not fix throttling on the individual pods."},
    {"level":4,"diff":3,"scenario":1,"q":"A team reports that JFR shows no hot methods and GC is healthy, but P99 latency is high and variable. CPU throttling metrics show 20% throttled time. The pod has `cpu.limits=500m, cpu.requests=200m`. What is the most precise diagnosis?","opts":["The service is memory-constrained, not CPU-constrained","The 500m CPU limit is too low for bursts — the JVM's JIT compiler and application threads are being throttled, causing unpredictable pauses unrelated to GC","The Kafka consumer is rebalancing frequently","HikariCP is exhausted","The readiness probe is timing out"],"ans":1,"fb":"With 20% throttled time and no GC or application-level hot spots in JFR, the bottleneck is the CPU limit. JIT compilation, safepoint operations, and burst processing all require CPU spikes above the baseline. With 500m limit on a pod that requests 200m, any burst hits the throttle. The fix: raise cpu.limits (e.g., to 1000m) or remove limits while keeping requests accurate. JFR would miss throttling time because threads are frozen at the OS level."},

    {"level":4,"diff":1,"scenario":2,"q":"A Kafka topic has 6 partitions and your service has 3 replicas, each with 1 consumer thread. How many consumer threads are active at peak?","opts":["3","6","9","12","1"],"ans":0,"fb":"With 6 partitions and 3 consumer instances (1 thread each), Kafka assigns 2 partitions per consumer. Only 3 threads are actively consuming — one per consumer instance. Having more partitions than consumer threads is fine (each thread handles multiple partitions), but you cannot have more active consumer threads than partitions."},
    {"level":4,"diff":2,"scenario":2,"q":"A Kafka topic processes financial events with strict ordering requirements per account. You need to scale consumers to handle volume spikes. What constraint must you preserve?","opts":["All events must go to a single partition to preserve global order","Events for the same account must go to the same partition — use account ID as the partition key, and scale partitions and consumers together","Order is not achievable with Kafka at scale","Consumers must use synchronous processing to preserve order","All consumers must share a single thread"],"ans":1,"fb":"Kafka guarantees ordering within a partition, not across partitions. For per-account ordering, partition by account ID (consistent hashing). Scaling means adding partitions (and consumers), but events for the same account always land on the same partition (same key = same partition). Global ordering across all accounts is not achievable at scale without a single partition — which defeats scaling."},
    {"level":4,"diff":3,"scenario":2,"q":"Consumer lag spikes during monthly batch jobs that produce 10x normal event volume. Lag clears after 2 hours. You need to halve that recovery time. What approach has the fewest production risks?","opts":["Increase partition count from 12 to 24 and add 12 consumer replicas immediately","Identify the bottleneck first (CPU, DB writes, or external calls), then tune the specific constraint — add consumer replicas if CPU-bound, batch DB writes if I/O-bound, or add circuit breaking if external calls are the limit","Double the consumer thread count per pod from 1 to 2","Reduce `max.poll.interval.ms` to force faster processing","Increase `max.poll.records` to 5000"],"ans":1,"fb":"Blindly adding replicas may help if CPU is the bottleneck but wastes resources if DB writes or external calls are saturated. Increasing consumer threads per pod may cause DB connection exhaustion. Doubling partition count requires a rebalance and cannot be done without downtime on some Kafka configurations. The correct approach: profile the bottleneck, then apply the targeted fix. Reducing `max.poll.interval.ms` risks triggering rebalances."},

    {"level":4,"diff":1,"scenario":3,"q":"What is 'safepoint bias' and how does it affect JVM latency measurements?","opts":["A JVM security feature that protects sensitive operations","JVM profilers can only sample threads at safepoints, causing profilers to under-represent work done between safepoints and over-represent safepoint-heavy code","A bias in GC towards promoting objects early","A Spring Boot feature for sampling request latency","A JVM optimisation that batches object allocations"],"ans":1,"fb":"Traditional JVMTI-based profilers sample only at safepoints (places where the JVM can stop all threads safely). Code that runs between safepoints (tight loops, JIT-compiled code) is undersampled or invisible. This causes profiler results to misrepresent where CPU time is actually spent. async-profiler avoids safepoint bias by using OS-level signals (AsyncGetCallTrace) to sample at any point."},
    {"level":4,"diff":2,"scenario":3,"q":"A service has P99 latency of 200ms but median is 5ms. JFR shows no GC pauses and CPU is not throttled. What JVM-level mechanism most commonly explains high tail latency without visible GC?","opts":["JVM startup time","Safepoint pauses — JVM operations like deoptimisation, class redefinition, or biased lock revocation cause stop-the-world pauses not reported as GC pauses","Too many HTTP threads","Database connection timeouts","Kafka consumer lag"],"ans":1,"fb":"Non-GC safepoint pauses (deoptimisation, biased lock revocation, class loading, JIT compilation) can cause stop-the-world pauses that do not show up in GC logs. These are visible in JFR under 'JVM - Runtime - Safepoint' events. P99 spikes with clean GC are a classic signal of safepoint overhead. Biased locking was removed in Java 21, but deoptimisation and revocation still occur."},
    {"level":4,"diff":3,"scenario":3,"q":"You need to reduce P99 latency variance on a service where most variance comes from GC pauses of 50–100ms every 30 seconds. The heap is 4GB. What is the most targeted fix?","opts":["Increase heap to 8GB to reduce GC frequency","Switch to ZGC — its concurrent collection eliminates stop-the-world pauses that cause the tail latency variance","Reduce `maximumPoolSize` to reduce GC pressure","Add more CPU to the pod","Reduce log verbosity to reduce I/O latency"],"ans":1,"fb":"Periodic 50–100ms stop-the-world GC pauses directly cause P99 variance. ZGC's design goal is sub-millisecond pauses by performing compaction and marking concurrently. Increasing heap size delays GC but does not eliminate the pauses — they may become longer when they do occur. More CPU helps GC run faster in G1 but does not eliminate stop-the-world. Pool size and logging have negligible effect on GC-induced latency."},

    {"level":4,"diff":1,"scenario":4,"q":"Service A uses all 10 connections in its HikariCP pool waiting for Service B to respond. Service B is also waiting on its pool. What is this pattern called?","opts":["A deadlock","Thread starvation","A connection pool cascade — pool exhaustion in one service blocks threads, which exhaust the pool in an upstream service","A Kafka consumer lag cascade","A GC cascade"],"ans":2,"fb":"Connection pool cascades (sometimes called thread pool cascades or dependency starvation) occur when slow or blocked downstream services cause upstream services' threads to hold connections while waiting. If the pool is exhausted, all new requests queue up, exhausting higher tiers. This is a distributed system failure mode, not a local deadlock. It is similar in structure to a thread pool cascade."},
    {"level":4,"diff":2,"scenario":4,"q":"You suspect a connection pool cascade between Service A and Service B. What metrics help you confirm the cascade direction?","opts":["CPU throttling metrics on both services","HikariCP `hikaricp.connections.pending` (waiting threads) and `hikaricp.connections.active` (in use) on both services, correlated with response time of Service B calls from Service A","GC pause duration on both services","Kafka consumer lag on both services","Pod restart counts"],"ans":1,"fb":"A cascade manifests as: Service B response time degrades → Service A threads hold connections longer waiting for B → Service A's `connections.active` and `connections.pending` rise → Service A's own response time degrades. Correlating `hikaricp.connections.pending` (queue depth) with upstream call latency pinpoints the direction and confirms it is a pool cascade, not an independent degradation."},
    {"level":4,"diff":3,"scenario":4,"q":"A cascade mitigation strategy involves adding a timeout on Service A's calls to Service B. The timeout is set to 2 seconds. HikariCP `connectionTimeout` is 30 seconds. Does this fully prevent the cascade?","opts":["Yes — the 2-second call timeout ensures connections are returned quickly","No — if 100 threads each wait 2 seconds before timing out, all 100 hold their connections for 2 seconds, still exhausting the pool during a degraded-B period","Yes — as long as any timeout exists, cascades cannot occur","No — the fix is to increase `maximumPoolSize` to 100","No — the only fix is to remove Service B from the critical path"],"ans":1,"fb":"A 2-second timeout bounds individual request latency but does not prevent pool exhaustion if the request rate is high enough. Under load, 100 concurrent threads each holding a connection for 2 seconds (waiting for B to time out) still exhausts a 10-connection pool for the full 2 seconds. The complete mitigation requires: short call timeouts + bulkhead isolation (separate thread pool for Service B calls) + circuit breaker to fail fast when B is degraded."}
  ]
};
