var TRACK_DESIGN = {
  "id": "design",
  "label": "Solution Design",
  "icon": "design",
  "desc": "Architecture and system design for distributed BaaS services. Covers API design, data modelling, event-driven patterns, and cross-team architectural decisions.",
  "levels": [
    {
      "num": 1, "name": "Foundations",
      "desc": "Understanding existing system designs and contributing to discussions with confidence.",
      "scenarios": [
        "Reading API contracts (OpenAPI specs) and integrating against them independently",
        "Following design discussions and understanding trade-offs being made",
        "Identifying whether a change requires a schema change, new endpoint, or event",
        "Reading and understanding Architecture Decision Records (ADRs)",
        "Articulating why a bug is a design problem, not just a code problem"
      ]
    },
    {
      "num": 2, "name": "Practitioner",
      "desc": "Designing features that span service boundaries and documenting those decisions clearly.",
      "scenarios": [
        "Designing multi-service interactions (API contracts, sync vs async, Kafka vs HTTP)",
        "Writing ADRs that explain context, decision, alternatives, and consequences",
        "Designing REST endpoints with correct HTTP verbs, status codes, and pagination",
        "Identifying aggregate roots, consistency boundaries, and data replication trade-offs",
        "Giving concrete design feedback in PRs and design docs"
      ]
    },
    {
      "num": 3, "name": "Advanced",
      "desc": "Designing systems that handle complex domains, failure modes, and regulatory constraints.",
      "scenarios": [
        "Designing audit and event sourcing strategies for regulated domains (PCI-DSS, SOX)",
        "Designing sagas (orchestration vs choreography) with compensation and idempotency",
        "Designing API versioning strategies and managing breaking changes",
        "Designing multi-tenancy patterns (data isolation, tenant context propagation)",
        "Designing Kafka retry and dead-letter strategies for external integrations"
      ]
    },
    {
      "num": 4, "name": "Specialist",
      "desc": "Owning cross-service designs end-to-end and raising the quality bar across your domain.",
      "scenarios": [
        "Leading cross-team design sessions and maintaining design coherence",
        "Redesigning system boundaries (CQRS, read models, caching) for scale",
        "Identifying reuse opportunities and proposing consolidation across teams",
        "Identifying systemic risks in designs (retry storms, thundering herds, ordering assumptions)",
        "Tracing a financial transaction end-to-end across all services for compliance"
      ]
    },
    {
      "num": 5, "name": "Expert",
      "desc": "Setting architectural standards for the organisation and leading the highest-complexity design work.",
      "scenarios": [
        "Identifying diverging architectural decisions across teams and driving standards",
        "Scoping major architectural shifts and presenting phased approaches to leadership",
        "Facilitating stuck design decisions by surfacing real trade-offs and hidden assumptions",
        "Leading technology evaluations (new messaging systems, service meshes, API gateways)",
        "Defining the solution design curriculum for the training programme"
      ]
    },
    {
      "num": 6, "name": "Authority",
      "desc": "Architectural governance, technology strategy, and building the organisation's design capability.",
      "scenarios": [
        "Leading architecture for new strategic directions (new markets, new BaaS products)",
        "Redesigning the architectural decision-making process (when ADRs are required, who's involved)",
        "Owning audit/regulatory responses about system design (data flows, failure handling)",
        "Producing structured technical debt assessments with sequenced improvement roadmaps",
        "Building shared architectural vocabulary (standards, design guild, reference architectures)"
      ]
    }
  ],
  "questions": [
    {"level":5,"diff":1,"scenario":0,"q":"You notice that three teams have independently built different patterns for propagating tenant context across service calls — one uses HTTP headers, one uses a thread-local, and one injects it via a Spring interceptor. What is the first thing an Expert should do before proposing a standard?","opts":["Document the three existing approaches, catalogue where each is used, and identify concrete problems each has caused in production","Immediately write an ADR mandating the HTTP header approach because it is the most portable","Ask each team to migrate to a shared library you write this week to unify the behaviour","Raise the divergence in the architecture guild and let the group vote on which pattern to adopt","Leave it alone because the approaches are functionally equivalent and standardisation has a cost"],"ans":0,"fb":"Before proposing a standard you must understand the full landscape: what exists, where it is used, and what real harm the divergence causes. Skipping this step leads to standards that miss edge cases or mandate migration work with unclear benefit. Calling a vote (D) without documented evidence produces uninformed decisions. Immediately writing a new library (C) risks creating a fourth pattern. Doing nothing (E) ignores compounding drift. An immediate ADR (B) without analysis may mandate the wrong approach.","context":{}},
    {"level":5,"diff":1,"scenario":0,"q":"Two teams are building event-driven flows on Kafka. Team A publishes domain events with full entity payloads; Team B publishes thin notification events and expects consumers to query back for state. A new team is about to start building a third consumer and asks which pattern to follow. What should an Expert say?","opts":["Tell them to follow Team B because thin events decouple producers from consumer data needs","Tell them to follow Team A because full payloads reduce the need for extra round-trips","Acknowledge both patterns have merit, explain the trade-offs, and flag that a platform decision is needed before the new team picks a direction","Tell them to implement both patterns and let their consumers choose what they need","Defer the decision to the new team's tech lead because it is their service boundary"],"ans":2,"fb":"When a third team enters and both patterns coexist, allowing them to pick freely entrenches the divergence. The Expert role is to surface the trade-offs (fat vs thin events: consumer coupling, schema versioning, query load) and drive a platform-level decision. Recommending one pattern without that discussion (A or B) is premature. Implementing both (D) creates more complexity. Deferring to the new tech lead (E) abdicates the Expert's responsibility to drive standards.","context":{}},
    {"level":5,"diff":2,"scenario":0,"q":"After auditing four services, you find each team has defined its own retry strategy for Kafka consumer failures: fixed delay, exponential backoff with different caps, and one team using no retry at all. You want to drive a standard. Which approach best balances consistency with team autonomy?","opts":["Mandate that all teams adopt exactly the same retry parameters immediately or they cannot deploy","Write a shared Spring Boot starter that provides a configurable retry and DLQ pattern with sensible defaults, let teams adopt it at their own pace, and set a deadline aligned to a platform release","Write an ADR documenting the recommended pattern and let teams adopt it whenever they choose","Ask each team to write their own ADR explaining their current approach and invite peer review","Only standardise teams whose retry bugs have caused incidents; leave the others alone"],"ans":1,"fb":"A shared starter library encodes the standard in code, making the right thing the easy thing, while configurable parameters preserve legitimate team differences. A hard deploy gate (A) is too coercive and creates friction without teaching. An ADR alone (C) is easy to ignore. Per-team ADRs (D) just documents divergence. Incident-triggered standardisation (E) is reactive and misses latent risk. The key Expert move is providing a paved path, not just a written rule.","context":{}},
    {"level":5,"diff":2,"scenario":0,"q":"You are running an architecture guild session. Two senior engineers from different teams argue for opposite pagination strategies: one prefers offset-based pagination, the other prefers cursor-based. Both have implemented their approach in production APIs. How do you facilitate the discussion toward a durable platform decision?","opts":["Ask the two engineers to each present a benchmark and let the fastest approach win","Adopt cursor-based pagination as the standard because it is the more modern approach","Frame the decision around concrete axes: dataset size, sort stability, client UX needs, and compliance requirements — then assess which strategy best fits the platform's dominant use cases","Decide by team size: whichever pattern more teams currently use becomes the standard","Treat them as equivalent and document both as acceptable, letting new teams choose freely"],"ans":2,"fb":"Architecture decisions should be grounded in the platform's actual constraints and use cases, not benchmarks in isolation or recency bias. Framing around axes (dataset size, sort stability, client needs, compliance) gives the guild a structured way to evaluate both patterns against reality. Defaulting to the majority pattern (D) entrenches the status quo regardless of merit. Accepting both (E) perpetuates the divergence. A benchmark alone (A) ignores non-performance trade-offs. 'More modern' (B) is not an engineering argument.","context":{}},
    {"level":5,"diff":2,"scenario":0,"q":"Three teams have diverged on how they model soft deletes: one uses a boolean deleted flag, one uses a deleted_at timestamp, and one uses a status enum with ACTIVE/ARCHIVED/DELETED states. A compliance audit is approaching and the auditors want consistent data retention evidence across the platform. What is the Expert's move?","opts":["Pick the boolean flag because it is the simplest and ask all teams to migrate before the audit","Tell the auditors that each team's approach is internally consistent and they should audit each service independently","Map all three approaches to the compliance requirement, identify whether any fails to meet retention and auditability needs, propose a minimum standard that satisfies compliance, and agree a migration sequence","Ask the compliance team to write the standard and hand it to engineering to implement","Only change the approaches that auditors explicitly flag as problems"],"ans":2,"fb":"The Expert bridges engineering reality and compliance requirements. The right move is to evaluate each existing pattern against what the audit actually requires — retention period traceability, recoverability, audit log completeness — rather than defaulting to the simplest or waiting for auditors to dictate. Mandating the boolean flag (A) may lose timestamp evidence. Deferring to compliance to write the spec (D) abdicates technical ownership. Reactive-only change (E) is high risk ahead of an audit.","context":{}},
    {"level":5,"diff":3,"scenario":0,"q":"You identify that two teams have independently solved idempotent Kafka consumer processing in incompatible ways: Team A stores a processed-event ID in the same PostgreSQL transaction as the business write; Team B checks a Redis cache before processing and relies on cache TTL for deduplication. A new compliance requirement demands that duplicate event processing must never result in double financial postings, with an auditable guarantee. Which response best represents Expert-level architectural leadership?","opts":["Mandate Team A's approach platform-wide because transactional deduplication is strictly stronger than cache-based TTL","Mandate Team B's approach because Redis is faster and reduces database write amplification","Evaluate both approaches against the compliance requirement: transactional deduplication provides durable, auditable guarantees whereas TTL-based cache cannot guarantee deduplication across restarts or evictions — propose transactional deduplication as the standard for financial flows, with a migration plan and a carve-out for non-financial consumers where TTL risk is acceptable","Ask each team to add compensating transactions so either approach can recover from duplicates","Treat this as an unsolved problem and recommend a third-party exactly-once framework"],"ans":2,"fb":"Expert-level leadership means mapping the technical differences to the compliance requirement precisely. Transactional deduplication (Team A) provides a durable, crash-safe guarantee because the idempotency record and business write commit atomically — this is auditable. Redis TTL (Team B) has a gap: cache eviction or a Redis restart before the TTL expires allows reprocessing. For financial postings under PCI-DSS/SOX, that gap is unacceptable. Mandating Team A without explaining the compliance rationale (A) is correct but incomplete as leadership. Compensating transactions (D) add complexity without addressing the root guarantee gap. A third-party framework (E) avoids the decision.","context":{}},
    {"level":5,"diff":3,"scenario":0,"q":"You discover that teams across the platform have adopted four different strategies for inter-service authentication: mutual TLS, JWT bearer tokens validated locally, JWT tokens validated via a central auth service on every request, and API keys stored in Kubernetes secrets. A security review is imminent. As the Expert responsible for driving standards, you need to decide how to handle this divergence. What is the most defensible approach?","opts":["Mandate mTLS for all inter-service calls because it is the strongest option","Accept all four approaches as long as each team can demonstrate they passed their last security review","Conduct a threat model for each authentication pattern against your platform's actual attack surface, identify which patterns create unacceptable risk such as long-lived API keys without rotation or unbounded central auth latency, define a standard for new services and high-risk flows, and produce a risk-tiered migration plan for existing services","Ask the security team to pick a standard and enforce it through CI gates","Standardise on JWT bearer tokens with local validation because it is stateless and scales well"],"ans":2,"fb":"Divergent authentication patterns require a threat-model-driven assessment, not a blanket mandate. mTLS (A) is strong but operationally expensive and may not be the right trade-off for all service-to-service calls on GKE where Workload Identity is available. Accepting all approaches if they passed prior reviews (B) ignores cumulative risk. Deferring to the security team (D) abdicates the Expert's role in translating security requirements into architectural decisions. Mandating stateless JWT (E) is reasonable but the right answer requires evaluating the actual attack surface. The Expert produces a risk-tiered decision with a migration plan, not a one-size-fits-all mandate.","context":{}},
    {"level":5,"diff":1,"scenario":4,"q":"You are tasked with defining the Solution Design curriculum for a multi-team engineering organisation. Which of the following best describes the first step?","opts":["Write a reading list of architecture books and distribute it to all engineers","Assess the current level distribution across teams using the placement quiz, then map curriculum topics to the gaps you find","Ask each tech lead what topics their team wants to learn","Run a series of ADR workshops and use attendance to gauge interest areas","Copy the curriculum from a well-known tech company's engineering blog and adapt the titles"],"ans":1,"fb":"A curriculum should be grounded in evidence of where engineers currently are and what gaps exist. The placement quiz provides structured level data; mapping curriculum to those gaps ensures the investment targets real needs. A reading list (A) is an output, not a starting point. Tech lead input (C) is useful but subjective and does not replace data. Workshop attendance (D) measures engagement, not skill gaps. Copying an external curriculum (E) ignores your platform's specific technology and compliance context.","context":{}},
    {"level":5,"diff":1,"scenario":4,"q":"When designing a learning module on 'Designing multi-service interactions' for Level 2 engineers, which format is most likely to build durable applied judgment rather than surface familiarity?","opts":["A 45-minute lecture covering the theory of synchronous vs asynchronous communication","A written case study where engineers read about a design decision another team made","A structured exercise where engineers design a real feature from a simplified version of the platform, defend their choices, and receive structured feedback","A quiz on REST vs Kafka trade-offs with multiple-choice questions","A recorded talk by an external speaker on microservice patterns"],"ans":2,"fb":"Durable judgment is built through practice with feedback, not passive exposure. A structured design exercise on a realistic platform scenario — followed by defence and critique — mirrors how engineers actually make decisions and reveals gaps that lectures and quizzes cannot. Lectures (A) and talks (E) build awareness but not application skill. Case studies (B) are useful but passive. MCQ quizzes (D) assess recall, not judgment. The Expert's role in curriculum design is choosing formats that match the competency being developed.","context":{}},
    {"level":5,"diff":2,"scenario":4,"q":"You notice that after three months of running design workshops, engineers can articulate trade-offs confidently in workshop settings but still produce weak ADRs in their actual PRs. What does this tell you about the curriculum design, and what should you change?","opts":["The engineers are not engaged enough — make the workshops mandatory and more frequent","The curriculum is working; ADR quality takes longer to improve than workshop performance","There is a transfer gap: the learning context (workshop) is too distant from the application context (real PR). Redesign so engineers write and review ADRs within their actual work, not in separate sessions","The ADR template is too complex — simplify it to three fields so engineers can fill it in faster","Add a separate ADR-writing module at the end of the curriculum to address the gap"],"ans":2,"fb":"When performance in training does not transfer to work, the curriculum has a context gap. Engineers learn in an artificial setting and the skills do not activate in the real setting. The fix is to embed learning in real work: review actual ADRs in PRs, pair engineers with a more senior reviewer on their next real design decision, or run critique sessions on ADRs they wrote for live features. Making workshops mandatory (A) increases dose without fixing the gap. Adding a separate module (E) still separates learning from application. Simplifying the template (D) addresses form, not skill. Claiming it will come (B) ignores the evidence.","context":{}},
    {"level":5,"diff":2,"scenario":4,"q":"You are designing the Level 3 curriculum module on sagas and compensation patterns. Two engineers on your review panel disagree: one argues engineers should learn orchestration-based sagas first because they are easier to reason about; the other argues choreography-based sagas should come first because the platform uses them more. How do you resolve this?","opts":["Defer to the more senior engineer on the panel","Teach orchestration first because all authoritative references present it that way","Design the module to start with the problem being solved — distributed transaction failure modes — then introduce both patterns side by side, using a real platform scenario to show when each is appropriate","Survey the team and teach whichever pattern the majority prefer","Teach choreography first because that is what the platform uses, and defer orchestration to a later optional module"],"ans":2,"fb":"The sequencing debate is a distraction from the real question: what mental model do engineers need first? Starting with the problem — what goes wrong in distributed transactions, what compensation means — gives engineers the 'why' before the 'how'. Presenting both patterns in contrast against a real scenario lets them understand trade-offs rather than memorising one approach. Deferring to seniority (A) or external references (B) treats the curriculum as a political or citation problem rather than a pedagogical one. Survey-driven curriculum (D) conflates preference with learning effectiveness.","context":{}},
    {"level":5,"diff":2,"scenario":4,"q":"You are asked to decide whether to include a module on 'Designing for PCI-DSS compliance' in the Level 3 Solution Design curriculum, or to leave compliance topics to a separate programme run by the security team. What is the Expert's reasoning?","opts":["Leave it to the security team — compliance is not a design topic","Include a full compliance certification module so engineers understand all PCI-DSS requirements","Include a design-focused module that covers how compliance shapes specific design decisions such as audit event schemas, data isolation boundaries, and retention patterns — rather than compliance rules in the abstract — and coordinate with the security team to avoid duplication","Add compliance as an optional reading list item so engineers can self-study if interested","Include compliance only for engineers working in the payments team; it is not relevant to the others"],"ans":2,"fb":"PCI-DSS compliance profoundly shapes design decisions on a BaaS platform — audit schemas, tenant data isolation, retention — and engineers need to understand those design implications to do Level 3 work. The Expert's curriculum decision is to teach compliance as a design constraint, not as a legal checklist, and to coordinate with the security team to avoid redundancy. Leaving it out entirely (A) creates engineers who make non-compliant design choices. A full certification module (B) is out of scope for a design curriculum. Optional reading (D) does not build reliable competency. Restricting it to payments (E) ignores cross-cutting concerns on a multi-tenant BaaS platform.","context":{}},
    {"level":5,"diff":3,"scenario":4,"q":"Six months after launching the Solution Design curriculum, quiz placement data shows engineers are advancing from Level 2 to Level 3 at roughly the expected rate, but almost none are reaching Level 4. The Level 3 modules have high satisfaction scores. What is the most likely explanation and what should you investigate first?","opts":["Level 4 is genuinely very hard and the plateau is expected; no action needed","The Level 3 satisfaction scores indicate the content is too easy — engineers feel good but are not being challenged enough to develop Level 4 skills","The placement quiz is miscalibrated at the Level 3 and Level 4 boundary — check whether Level 4 questions are significantly harder than intended","Investigate whether the Level 3 curriculum covers the competencies that actually gate Level 4 progression, and whether engineers have opportunities to practise Level 4 behaviours such as leading cross-team design sessions in their real work","Add more Level 3 modules to give engineers longer at that level before attempting Level 4"],"ans":3,"fb":"High satisfaction at Level 3 with a plateau at Level 4 is a classic sign that the curriculum is teaching the content of Level 3 but not developing the behaviours needed for Level 4. Level 4 competencies — leading cross-team design sessions, identifying systemic risk, proposing consolidation — require opportunities to practise in real work; they cannot be developed in a classroom alone. The Expert investigates whether those opportunities exist and whether the Level 3 curriculum bridges to them. Quiz miscalibration (C) is worth checking but is a secondary hypothesis. Adding more Level 3 content (E) deepens where engineers already are rather than bridging the gap. Treating the plateau as expected (A) dismisses evidence without investigation.","context":{}},
    {"level":5,"diff":3,"scenario":4,"q":"You have built a Solution Design curriculum and run it for a year. A VP of Engineering asks you to demonstrate its ROI. You have placement quiz data, workshop attendance records, and satisfaction scores. Which approach best demonstrates meaningful impact?","opts":["Show the average satisfaction score across all modules (4.3 out of 5.0) and the number of engineers who completed the programme","Show a graph of placement level distribution before and after the programme, correlated with a reduction in architecture-related incidents and rework identified in post-mortems","Count the number of ADRs written by engineers who attended the curriculum versus those who did not","Ask engineers to self-report whether the curriculum improved their design confidence and present the results","Show that the curriculum cost less per engineer than comparable external training providers"],"ans":1,"fb":"ROI for a skills programme requires connecting learning outcomes to business outcomes. Level distribution movement from placement data is a leading indicator; reduced architecture-related incidents and rework from post-mortems are lagging indicators that connect skill improvement to real impact. Satisfaction scores (A) measure engagement, not learning or impact. ADR count (C) measures activity, not quality. Self-reported confidence (D) is subjective and susceptible to the Dunning-Kruger effect. Cost comparison (E) measures efficiency, not value. The Expert frames impact in terms the VP cares about: the quality of engineering decisions and their downstream effects.","context":{}},
    {"level":6,"diff":1,"scenario":2,"q":"A PCI-DSS auditor asks your team to produce a data flow diagram showing how cardholder data moves through the platform. Which artifact best satisfies this requirement?","opts":["A sequence diagram showing every internal API call between microservices","A system-level data flow diagram annotated with trust boundaries, encryption in transit, and storage classification for each data element","An OpenAPI specification for each service that handles payment data","A network topology diagram showing GKE pod-to-pod communication","A Kafka topic map showing all producers and consumers"],"ans":1,"fb":"PCI-DSS Requirement 1 mandates network diagrams and data flow diagrams that show all cardholder data flows, including trust boundaries and controls at each boundary. An annotated system-level DFD with encryption status and storage classification directly addresses this. Sequence diagrams are too granular and implementation-focused. OpenAPI specs describe interfaces, not data movement. Network topology and Kafka maps are partial views that miss the end-to-end cardholder data scope auditors require.","context":{"PCI-DSS Req 1.2.4":"Maintain accurate network diagrams that show all connections to cardholder data environment","PCI-DSS Req 1.2.1":"Document all services, protocols, and ports including business justification"}},
    {"level":6,"diff":1,"scenario":2,"q":"During a SOX audit, the auditor asks how your platform ensures that no single engineer can both approve and deploy a change to a financial calculation service. Which design control directly addresses this segregation-of-duties requirement?","opts":["Enforcing a minimum PR approval count of two reviewers in GitHub branch protection rules","Requiring separate individuals to hold the 'approve PR' and 'trigger production deployment' roles, enforced by your CI/CD pipeline and RBAC","Running automated test suites on every PR to validate financial calculation correctness","Requiring all financial service changes to include an ADR signed off by an architect","Storing all deployment audit logs in Cloud Logging with a 7-year retention policy"],"ans":1,"fb":"Segregation of duties (SOD) for SOX requires that approval and execution of a control are performed by different individuals, enforced by a system control rather than convention. Separating the 'approve' and 'deploy' roles in RBAC, enforced by the pipeline, is the canonical SOD control. Two reviewers alone does not prevent the same person from approving and deploying if they hold deployment rights. Automated tests, ADRs, and audit logs are good complementary controls but do not enforce SOD by themselves.","context":{"SOX Section 404":"Management must assess internal controls over financial reporting","SOD principle":"No single individual should control all phases of a transaction"}},
    {"level":6,"diff":2,"scenario":2,"q":"A regulator requests evidence that your multi-tenant platform correctly isolates one tenant's financial data from another in the event of a code defect. You have row-level security (RLS) in PostgreSQL and tenant context propagated via a Spring interceptor. What is the most compelling evidence package to produce?","opts":["The OpenAPI specifications for all tenant-scoped endpoints, annotated with the tenant ID parameter","A penetration test report from an accredited third party demonstrating failed cross-tenant data access attempts, alongside RLS policy definitions and integration test results that assert isolation","A description of the Spring interceptor code that sets the tenant context on every request","Database query logs showing that all queries include a tenant_id predicate","An architecture diagram showing the RLS layer between the application and the database"],"ans":1,"fb":"Regulators require evidence that controls are effective, not just that they exist. A penetration test from an accredited party provides independent validation of the isolation claim. Combined with RLS policy definitions (the control design) and integration tests (continuous verification), this constitutes a defence-in-depth evidence package. OpenAPI specs and architecture diagrams describe intent, not effectiveness. Query logs are incomplete without proof they are exhaustive. Spring interceptor code shows one layer but not the database-level enforcement that prevents bypassed application code from leaking data.","context":{"Control design vs. operating effectiveness":"Auditors assess both whether a control is designed correctly and whether it actually operates","Defence in depth":"Multiple independent controls are more credible than a single mechanism"}},
    {"level":6,"diff":2,"scenario":2,"q":"Your platform processes payment events via Kafka. An auditor asks: what happens to a payment event if the consumer crashes after committing the Kafka offset but before persisting the database record? How should you document this failure mode for a regulatory response?","opts":["State that Kafka's at-least-once delivery guarantees the message will not be lost","Acknowledge the at-most-once loss window, document the compensating control (idempotency key on re-insertion and a reconciliation job that detects gaps using sequence numbers), and quantify the maximum exposure window based on consumer commit interval","State that Cloud SQL's ACID guarantees prevent data loss once a record is written","Describe the Kafka consumer group rebalancing mechanism and how it assigns partitions to healthy consumers","State that the platform uses transactions, so either both the offset commit and the database write succeed or neither does"],"ans":1,"fb":"This is the classic at-most-once loss scenario: offset committed, application crashed, message not persisted. The honest and correct regulatory response acknowledges the gap exists, then documents the compensating controls that bound and detect it. Idempotency keys and reconciliation jobs are the standard mitigation pair. Quantifying the maximum exposure window (commit interval) shows the risk is understood and bounded. Option A is wrong — at-least-once means the broker will re-deliver uncommitted offsets, not committed ones. Option C is irrelevant to the Kafka commit/DB write ordering problem. Option D describes recovery mechanics, not the failure mode. Option E describes a 2-phase commit that the question explicitly rules out by the scenario.","context":{"Commit interval":"If offset is committed before DB write, a crash in between loses the event","Reconciliation":"A batch job that compares expected sequence against persisted records can detect gaps"}},
    {"level":6,"diff":2,"scenario":2,"q":"A PCI-DSS QSA asks you to demonstrate how your system detects and alerts on anomalous access to cardholder data — for example, an internal service suddenly querying 10x more records than its baseline. Which design best satisfies this requirement?","opts":["Enable Cloud SQL audit logs and store them in Cloud Logging with a long retention policy","A combination of Cloud SQL data access audit logs ingested into a SIEM, with anomaly detection rules that alert when per-service query volume exceeds a rolling baseline threshold, linked to an incident response runbook","Implement application-level logging that records every query a service executes, stored in the service's own database","Configure Cloud Monitoring alerts on total Cloud SQL connection count spikes","Require all engineers to review Cloud SQL audit logs weekly and sign off that no anomalies were found"],"ans":1,"fb":"PCI-DSS Requirement 10 requires automated log review and alerting on anomalies — manual weekly review does not satisfy automated detection. A SIEM with anomaly detection rules on per-service access volume directly meets the spirit and letter of the requirement. Storing logs without alerting satisfies retention but not detection. Total connection count is too coarse a signal to detect per-service data over-access. Application-level logs in the service's own database create a conflict of interest and are not independent audit evidence. The SIEM approach provides independent evidence and automated detection.","context":{"PCI-DSS Req 10.7":"Detect and alert on failures of critical security controls","PCI-DSS Req 10.6":"Review logs and security events to identify anomalies"}},
    {"level":6,"diff":3,"scenario":2,"q":"During preparation for a regulatory examination, counsel asks you to produce a written response explaining how the system handles a scenario where a Kafka consumer processes a payment event, the downstream bank rejects the payment, but the rejection message is lost before the platform records it. The regulator's concern is undetected financial exposure. What is the architecturally correct response?","opts":["Explain that Kafka's durable log means the rejection message can always be replayed from the broker","Explain that the platform's at-least-once Kafka delivery guarantees the rejection will eventually arrive","Describe the end-to-end idempotency design: the payment is held in a PENDING state, a reconciliation process polls the bank's status API for any event that has not transitioned within an SLA window, and a dead-letter process escalates unresolvable cases with an audit trail — quantifying the maximum undetected exposure window","State that TLS encryption in transit prevents messages from being lost between the bank and the platform","Describe the retry policy on the Kafka consumer and the exponential backoff configuration"],"ans":2,"fb":"The failure mode here is that the external bank's rejection response is lost before the platform receives or persists it — this is outside Kafka's delivery guarantees, which only apply to the internal broker. The correct architectural response is a reconciliation loop against the authoritative external source (the bank's status API), combined with a PENDING state that forces explicit resolution. Quantifying the SLA window bounds the maximum exposure period. Options A and B misapply Kafka guarantees to a channel external to the broker. TLS prevents eavesdropping but not message loss. Retry policy addresses internal consumer retries, not external response loss. A regulator will specifically probe whether the platform detects unprompted failures — reconciliation is the answer.","context":{"External channel reliability":"Kafka guarantees apply only within the broker; external HTTP responses are a separate reliability domain","PENDING state pattern":"Holds a transaction in an unresolved state until positive confirmation or timeout-triggered reconciliation"}},
    {"level":6,"diff":3,"scenario":2,"q":"Your engineering leadership is asked by a regulator to provide a formal written response to the question: 'How does your platform ensure that a change to a financial calculation cannot be deployed to production without a complete audit trail from code commit to live service?' You must write a response that is both technically accurate and audit-defensible. Which response is strongest?","opts":["Describe the Git branching strategy and explain that all changes go through pull requests","State that all production deployments are logged in Cloud Logging with timestamps and deployer identity","Provide a control narrative describing the end-to-end chain: signed commits linked to a PR with required approvals, a CI pipeline that produces a provenance attestation (SLSA), an image registry that stores signed artefacts, and a GKE deployment that rejects unsigned images — with audit log evidence retained for the required period and a quarterly control test","Reference the company's change management policy document and state that all changes follow this policy","Describe the automated test suite that runs on every PR and the code coverage thresholds required for merge"],"ans":2,"fb":"An audit-defensible response must demonstrate a verifiable, tamper-resistant chain of custody from source code to production — not just describe process or point to a policy. The strongest response narrates the technical control chain (signed commits to approved PR to provenance attestation to signed image to admission control) with evidence retention and periodic control testing. This satisfies the auditor's need to see both control design and operating effectiveness. A branching strategy and policy document describe intent. Deployment logs provide partial evidence but not the full chain. Test coverage addresses quality, not integrity of the deployment chain. SLSA-based provenance is increasingly the standard regulators expect for software supply chain integrity.","context":{"SLSA":"Supply-chain Levels for Software Artifacts — a framework for attestation of build provenance","Control narrative":"A written description of who does what, when, and how evidence is retained — required for audit responses"}},
    {"level":6,"diff":1,"scenario":3,"q":"You are asked to lead a technical debt assessment across the platform. What is the correct first step before scoring or sequencing any remediation work?","opts":["Ask each team to estimate story points for rewriting their most painful services","Run static analysis tools across all repositories and sort findings by severity","Establish a consistent taxonomy for classifying technical debt (e.g. architecture debt, design debt, code debt, test debt, operational debt) so that findings across teams can be compared and prioritised on the same scale","Interview senior engineers about which parts of the codebase they are most afraid to change","Identify the three highest-traffic services and focus the assessment on those"],"ans":2,"fb":"A structured assessment requires a shared language before any scoring or sequencing can be meaningful. Without a consistent taxonomy, teams will report debt in incomparable terms — one team's 'high' is another's 'medium', and architectural drift cannot be compared with test coverage gaps. Establishing a taxonomy first ensures the assessment produces a comparable, actionable dataset. Story point estimates and static analysis are useful inputs but cannot be compared across teams without a shared framework. Engineer interviews surface valuable signal but are anecdotal without structure. Focusing only on high-traffic services produces an incomplete picture and misses high-risk low-traffic paths such as compliance-critical flows.","context":{"Debt taxonomy":"Common categories: architecture, design, code, test, documentation, operational, dependency","Comparability":"Assessments that lack a shared scale cannot produce a defensible prioritisation"}},
    {"level":6,"diff":1,"scenario":3,"q":"When sequencing a technical debt remediation roadmap, which factor most strongly justifies placing a debt item early in the sequence — ahead of items with higher remediation cost?","opts":["The debt item was introduced the longest time ago","The debt item is in the service with the largest team headcount","The debt item is a blocking dependency for multiple higher-priority improvements, so deferring it compresses the value of subsequent items","The debt item was raised by the most senior engineer on the team","The debt item has the most comments in the codebase explaining its problems"],"ans":2,"fb":"Sequencing a roadmap requires understanding dependency chains, not just individual item cost or age. A blocking dependency that gates multiple downstream improvements has a multiplier effect: its deferral delays not just its own resolution but everything that depends on it. This is the classic 'pebble in the stream' pattern — small foundational changes that unlock large subsequent value. Age, team size, seniority of the raiser, and comment volume are all weak signals with no necessary relationship to remediation sequencing logic.","context":{"Critical path":"The sequence of dependencies that determines the minimum project duration","Opportunity cost":"Deferring a blocking item delays all dependent improvements simultaneously"}},
    {"level":6,"diff":2,"scenario":3,"q":"You are producing a technical debt assessment for a platform that has accumulated significant schema coupling — multiple services share the same PostgreSQL schema and write directly to each other's tables. How should you represent this in the roadmap to make the business case for remediation?","opts":["List each shared table as a separate debt item with an estimated refactoring cost in developer-days","Frame the debt as an incident risk multiplier: show historical incidents where schema coupling caused cascading failures, estimate the blast radius of the next likely incident, and model the cost of continued coupling (incident cost times frequency) against the one-time remediation cost","Recommend that all services be rewritten to use separate databases immediately","Describe the schema coupling technically and ask engineering managers to assess its priority","Add the schema coupling to a backlog and flag it for consideration in the next planning cycle"],"ans":1,"fb":"To make a credible business case at authority level, technical debt must be expressed in terms leadership can act on: risk, cost, and expected value of remediation. Framing coupling as an incident risk multiplier — with historical evidence, blast radius modelling, and a cost comparison — converts an abstract technical concern into a decision with quantified stakes. Listing tables as individual items fragments the narrative and loses the systemic risk picture. Recommending immediate full rewrites lacks a phased approach and will not be funded. Delegating priority assessment to managers without a structured framing abdicates the authority responsibility. Backlog-and-defer is the pattern that created the debt in the first place.","context":{"Schema coupling blast radius":"A migration on a shared schema can break all services writing to it simultaneously","Cost of delay":"Debt that increases incident frequency has a compounding cost that can be quantified"}},
    {"level":6,"diff":2,"scenario":3,"q":"Your technical debt roadmap proposes decomposing a large monolithic Spring Boot service into smaller services over 18 months. Leadership asks how you will ensure the platform does not degrade during the transition. What sequencing principle should anchor the roadmap?","opts":["Extract the highest-traffic endpoints first to maximise early performance gains","Extract the simplest services first to build team confidence before tackling core domains","Sequence extractions so that each phase leaves the system in a fully operational, independently deployable state — using strangler fig with feature flags and parallel-run validation before cutting over","Freeze feature development on the monolith while the decomposition is in progress to avoid moving targets","Run the monolith and new services simultaneously indefinitely to reduce risk"],"ans":2,"fb":"The strangler fig pattern with incremental cut-overs is the canonical approach to safe decomposition: each extraction leaves the system shippable, no phase produces a half-migrated state that blocks production. Feature flags allow parallel running with rollback, and parallel-run validation confirms correctness before traffic switches. Extracting high-traffic endpoints first optimises for performance but ignores correctness risk. Extracting simple services first is a reasonable heuristic but insufficient as a sequencing principle — it does not guarantee operational continuity. Freezing feature development for 18 months is commercially unacceptable. Running both indefinitely is not a transition strategy; it doubles operational complexity.","context":{"Strangler fig":"Incrementally replace components by routing traffic to new implementations while the old one still runs","Parallel run":"Both old and new implementations process the same requests; outputs are compared before cutover"}},
    {"level":6,"diff":2,"scenario":3,"q":"A technical debt assessment identifies that 40% of the platform's Kafka consumers lack idempotency guards, creating a risk of duplicate financial records during rebalancing. How should you scope and sequence the remediation in the roadmap?","opts":["Schedule a single 2-week sprint to add idempotency keys to all consumers simultaneously","Triage consumers by financial impact: address consumers that write financial records first with idempotency keys and deduplication logic, then address non-financial consumers in order of blast radius, with each phase gated by integration tests that inject duplicate events","Recommend switching to exactly-once Kafka semantics (EOS) as a platform-wide fix that avoids consumer-level changes","Accept the risk as a known limitation and document it in the architecture decision record","Ask each team owning a consumer to prioritise the fix in their own backlog"],"ans":1,"fb":"Risk-based sequencing is the correct approach: financial record consumers carry the highest regulatory and financial exposure and must be remediated first. Gating each phase with integration tests that inject duplicate events confirms the control is working before moving on — this is the kind of evidence trail that supports both operational confidence and potential audit inquiries. A single sprint for all consumers creates a large parallel change risk with many untested interactions. Platform-wide EOS is a valid long-term goal but is a significant infrastructure change that does not address existing consumers quickly. Accepting the risk for financial data is not defensible under PCI-DSS/SOX. Delegating to individual team backlogs without a coordinated roadmap means the highest-risk items may never be addressed.","context":{"Idempotency key pattern":"Store the event ID; reject or ignore re-insertions of the same ID","EOS (exactly-once semantics)":"Kafka's transactional producer/consumer API — eliminates duplicates but requires infrastructure and code changes"}},
    {"level":6,"diff":3,"scenario":3,"q":"You present a technical debt roadmap to the CTO. The roadmap recommends 6 months of primarily debt remediation with limited new feature work. The CTO pushes back, arguing that the business cannot afford 6 months without feature delivery. How should you respond to maintain the integrity of the assessment while accommodating the business constraint?","opts":["Reduce the roadmap to 3 months by cutting the lower-priority debt items and accepting the residual risk","Propose an interleaved model: each sprint allocates a fixed percentage of capacity to debt remediation (e.g. 30%) run in parallel with feature work, with explicit checkpoints where debt reduction metrics are reviewed and the allocation adjusted — and show the model's projected impact on feature velocity over time as debt is reduced","Agree to defer all debt work until after the next major release to avoid conflict with the CTO","Escalate the disagreement to the board, framing it as a risk management decision","Propose that the debt roadmap is handed to a separate 'platform team' so the product teams can continue feature work uninterrupted"],"ans":1,"fb":"The authority-level skill here is bridging technical integrity with business reality. An interleaved model with a fixed capacity allocation is the canonical resolution: it does not abandon the debt work (which would leave the risk unaddressed) but makes it compatible with continued feature delivery. Showing how reduced debt improves future velocity reframes remediation as investment, not cost — which is the persuasive framing for a CTO. Cutting items to fit a timeline ignores the risk rationale that justified their inclusion. Deferring all debt work perpetuates the cycle that created the problem. Escalating to the board is disproportionate for this decision. A separate platform team can work for some categories of debt but is not a universal answer and often creates coordination overhead that slows both tracks.","context":{"Debt remediation capacity model":"A sustained 20-30% allocation compounds into significant debt reduction over quarters without blocking features","Velocity impact of debt":"Studies consistently show that unaddressed architectural debt reduces feature delivery speed over time"}},
    {"level":6,"diff":3,"scenario":3,"q":"You are finalising a structured technical debt assessment for the platform. The document will be reviewed by engineering leadership, product leadership, and the board's risk committee. Which structure makes the document most effective across all three audiences?","opts":["A single detailed technical appendix with code examples and architectural diagrams, presented in full to all audiences","An executive summary with risk and cost framing, a prioritised roadmap with business justification for each phase, and a technical appendix with architectural detail — each section written for its audience with explicit cross-references","A slide deck with one slide per debt item, sorted by team ownership","A spreadsheet with debt items scored on a 1-5 scale for severity, effort, and risk, shared with all audiences","Separate documents for each audience with no shared structure, written independently"],"ans":1,"fb":"A well-structured assessment for a mixed audience requires layered communication: the executive summary speaks to risk and investment in terms the board's risk committee and product leadership can act on; the prioritised roadmap with business justification bridges technical and product leadership; the technical appendix gives engineering leadership the depth to challenge and validate the analysis. Cross-references allow any reader to drill into detail without wading through it. A single technical document is inaccessible to non-engineers. A per-item slide deck fragments the systemic narrative. A spreadsheet conveys scores but not reasoning. Separate independent documents create inconsistency and prevent cross-audience alignment, which is critical when seeking board-level approval for remediation investment.","context":{"Layered documentation":"Executive summary then decision-maker narrative then technical evidence — each layer self-contained but linked","Risk committee framing":"Boards respond to quantified risk, not technical descriptions; frame debt as likelihood times impact"}}
  ]
};
