var TRACK_CLOUD = {
  "id": "cloud",
  "label": "Cloud & Observability",
  "icon": "cloud",
  "desc": "GCP, GKE, and the full observability stack: Cloud Monitoring, OpenTelemetry, Grafana, structured logging, and distributed tracing.",
  "levels": [
    {
      "num": 1, "name": "Foundations",
      "desc": "Reading what the platform is telling you and navigating GCP without getting lost.",
      "scenarios": [
        "Reading Grafana dashboards and distinguishing real alerts from noise",
        "Using kubectl to diagnose pod restarts (OOM, probe failures, crash loops)",
        "Using Cloud Logging to filter and find specific log entries",
        "Following runbook triage steps and escalating with useful context",
        "Reading Cloud SQL metrics dashboards (CPU, connections, storage)"
      ]
    },
    {
      "num": 2, "name": "Practitioner",
      "desc": "Instrumenting your service correctly and contributing to the team's observability setup.",
      "scenarios": [
        "Configuring GKE resource requests/limits and verifying service health in Cloud Monitoring",
        "Adding structured log statements with trace ID, tenant ID, and operation context",
        "Instrumenting custom metrics with Micrometer and building Grafana panels",
        "Using distributed tracing (Cloud Trace / Grafana Tempo) to follow requests across services",
        "Defining alert conditions with appropriate thresholds and runbook links"
      ]
    },
    {
      "num": 3, "name": "Advanced",
      "desc": "Diagnosing complex production issues across multiple services and owning the observability for a domain.",
      "scenarios": [
        "Correlating distributed traces with metrics to diagnose cross-service latency",
        "Investigating GKE node-level resource issues (throttling, pod scheduling)",
        "Tuning OpenTelemetry configuration (sampling, cardinality, noisy spans)",
        "Designing golden-signals dashboards for business-critical flows",
        "Reading and modifying Terraform modules for GKE and Cloud SQL"
      ]
    },
    {
      "num": 4, "name": "Specialist",
      "desc": "Owning the observability platform for the domain and ensuring the team can operate services in production with confidence.",
      "scenarios": [
        "Leading SLO/SLI definition and error budget management for critical services",
        "Analysing GCP cost breakdowns and proposing concrete optimisations",
        "Designing zero-downtime deployment sequencing with observability checkpoints",
        "Producing reusable observability guides (logging, metrics, tracing, alerts, dashboards)",
        "Planning and executing Cloud SQL maintenance with minimal disruption"
      ]
    },
    {
      "num": 5, "name": "Expert",
      "desc": "Setting observability and cloud standards for the organisation and mentoring teams through complex production scenarios.",
      "scenarios": [
        "Defining org-wide instrumentation standards and driving adoption",
        "Taking incident commander role for major cross-team incidents",
        "Leading evaluations of new observability tools against current stack",
        "Analysing GKE platform costs and modelling optimisation scenarios for leadership",
        "Defining runbook standards and running peer-review sessions"
      ]
    },
    {
      "num": 6, "name": "Authority",
      "desc": "Cloud platform strategy, reliability engineering at the organisational level, and technology direction.",
      "scenarios": [
        "Leading long-term GCP strategy (managed vs GKE vs serverless, multi-region)",
        "Designing and running DR drills with success criteria and gap analysis",
        "Owning the cloud cost narrative at the executive level",
        "Producing audit evidence for security event detection and response",
        "Leading platform capability rollouts that teams adopt because they're useful"
      ]
    }
  ],
  "questions": [
    {"level":4,"diff":2,"scenario":3,"q":"You are defining the standard OTEL Java agent configuration for all Spring Boot services on GKE. Which configuration properties are essential to include in the platform baseline?","opts":["Only otel.service.name — all other settings have sensible defaults","otel.service.name, otel.exporter.otlp.endpoint (pointing to the shared collector), otel.resource.attributes (including environment and version), and otel.traces.sampler with the agreed sampling configuration — these define identity, destination, context, and sampling policy","otel.traces.exporter=zipkin and otel.metrics.exporter=prometheus — these match the existing monitoring stack","Set otel.javaagent.enabled=false and instrument manually — auto-instrumentation creates too much overhead for production","otel.service.name and otel.traces.sampler=always_on — capture all traces in production"],"ans":1,"fb":"A platform baseline OTEL config must cover: (1) identity: otel.service.name (unique per service), (2) destination: otel.exporter.otlp.endpoint (the shared OTEL collector endpoint — do not let services export directly to backends), (3) context: otel.resource.attributes with environment, service.version, and team label, (4) sampling: otel.traces.sampler with the platform-agreed policy (not always_on in high-volume production). This ensures all services are discoverable in traces, export to the right place, and carry enough context for cross-service investigation.","context":{"Essential config":"service.name, exporter endpoint, resource attributes, sampler policy"}},
    {"level":4,"diff":2,"scenario":3,"q":"A team asks whether to use a pre-built Grafana dashboard JSON from Grafana.com versus building a custom one. What guidance should your observability guide give?","opts":["Always use community dashboards — they are battle-tested and require no maintenance","Always build custom dashboards — community dashboards are unreliable and poorly maintained","Use community dashboards as a starting point for infrastructure metrics (JVM, GKE node metrics) where metric names are standardized. Build custom dashboards for business flows and service-specific SLIs where metric names, labels, and business context are service-specific — the community dashboard will not know your service's business metrics","The choice does not matter — Grafana dashboards are interchangeable as long as the data source is configured","Use community dashboards for all services and suppress panels that are not applicable using dashboard permissions"],"ans":2,"fb":"Community dashboards work well for standardized metrics: JVM heap/GC (micrometer-jvm-extras uses standard names), Kubernetes node metrics (from node-exporter), and HikariCP metrics. These metric names are consistent across services. Business metrics — payment throughput, tenant-level error rates, Kafka consumer lag for specific topics — require custom dashboards because metric names, label values, and business context are service-specific. The observability guide should provide a template for the custom business dashboard with the standard structure (golden signals + service-specific panels).","context":{}},
    {"level":4,"diff":2,"scenario":3,"q":"You are writing the alerts section of the observability guide. A team asks whether to alert on CPU utilization. What is the correct guidance?","opts":["Yes — alert when CPU exceeds 80% for more than 5 minutes on any pod","No — CPU is not a user-facing signal. Alert on symptoms (error rate, latency) not causes. High CPU may or may not affect users. If CPU throttling is causing latency, the latency alert fires first. Add CPU as a dashboard metric for investigation, not as a primary alert","Alert on CPU only for database pods — application pods can tolerate high CPU without user impact","Alert when CPU exceeds 50% — this gives enough lead time before user impact","CPU alerts should fire at 95% with a 1-minute window to catch only the most severe cases"],"ans":1,"fb":"Alerting on CPU directly leads to alert fatigue — CPU spikes are common during GC, batch processing, or traffic bursts and often have no user impact. The SRE principle: alert on symptoms (what the user experiences) not causes (what the system is doing). Error rate and latency alerts are symptom-based — they fire when users are actually affected. CPU is a cause metric useful for investigation and dashboards. Exception: alert on CPU throttling specifically (container_cpu_cfs_throttled_seconds_total rate) if you know it correlates with latency in your service.","context":{}},
    {"level":4,"diff":3,"scenario":3,"q":"You are producing the Grafana dashboard standard for the platform. Teams must use dashboard-as-code (dashboard JSON stored in git). What operational problem does this solve and what tooling pattern enables it?","opts":["Dashboard-as-code prevents unauthorized dashboard edits — Grafana does not have role-based access control","Storing dashboard JSON in git enables version history, peer review of dashboard changes, automated deployment via CI/CD (e.g. Grafana provisioning or Terraform grafana_dashboard resource), and reproducible dashboard environments. It prevents dashboard drift where production Grafana differs from what teams expect and cannot be recreated after data loss","Dashboard-as-code is only necessary for dashboards shared across teams — individual team dashboards should be created in the UI","The main benefit is cost reduction — Grafana charges per dashboard when using managed Grafana (Grafana Cloud)","Dashboard-as-code enables Grafana to auto-generate dashboards from service definitions — no manual dashboard creation needed"],"ans":1,"fb":"Dashboard-as-code solves several operational problems: (1) auditability — who changed what and when, (2) reproducibility — dashboards can be recreated from git after accidental deletion or migration, (3) consistency — PR review ensures dashboards meet standards before production, (4) multi-environment — the same dashboard JSON parametrized by datasource variable deploys to staging and production. Implementation: store JSON in git, deploy via Grafana's provisioning (configmap mounted into Grafana pod), or use the Terraform grafana_dashboard resource in the IaC pipeline.","context":{}},
    {"level":4,"diff":3,"scenario":3,"q":"The observability guide needs to address how teams should instrument multi-step business transactions (e.g. a payment flow: validate → reserve → charge → notify). What is the recommended OpenTelemetry instrumentation pattern?","opts":["Emit one span per HTTP request — the service boundary spans are sufficient for tracing","Create a parent span for the overall transaction and child spans for each step (validate, reserve, charge, notify). Add business attributes to spans: tenant_id, payment_id, amount_cents, step_result. This allows the trace to show the full transaction flow, timing of each step, and which step failed — enabling both performance analysis and business debugging","Use log correlation instead of spans for business transactions — spans are for infrastructure, logs are for business events","Create metrics for each step (payment_validate_duration, payment_charge_duration) instead of spans — metrics are cheaper than traces at scale","Instrument only the slow steps — adding spans to all steps creates too much trace overhead"],"ans":1,"fb":"For multi-step business transactions, manual span creation with business context is the correct pattern. The OTEL Java API: `Span span = tracer.spanBuilder('payment.charge').startSpan(); span.setAttribute('payment.id', paymentId); span.setAttribute('tenant.id', tenantId)`. Child spans form a waterfall showing step timing. Business attributes (payment_id, amount, step outcome) make traces useful for both SRE debugging and business analysis. This is superior to metrics-only (which shows timing but not which specific payment failed) and logs-only (which cannot show the full flow waterfall).","context":{}},
    {"level":4,"diff":3,"scenario":3,"q":"An engineer asks why the observability guide recommends using recording rules in Prometheus for SLI calculations rather than computing them directly in Grafana dashboard queries. What is the correct reasoning?","opts":["Grafana cannot execute PromQL queries — it requires pre-computed metrics from recording rules","Recording rules pre-compute expensive PromQL expressions at the Prometheus server on a regular interval. SLI calculations (error budget burn rate, multi-window rate calculations) queried across 30-day windows are expensive — running them live in Grafana for every dashboard refresh adds query latency and Prometheus load. Recording rules also enable alerting on the same pre-computed values, ensuring alert and dashboard metrics are identical","Recording rules are required for SLI calculations — Prometheus does not support multi-window PromQL in ad-hoc queries","Recording rules automatically adjust SLO thresholds based on historical data — this is not possible with ad-hoc queries","Grafana's query caching handles this — recording rules and ad-hoc queries are equivalent in practice"],"ans":1,"fb":"Recording rules pre-compute expensive or frequently-used queries at a configured interval (e.g. every 30s) and store results as new metrics. Benefits for SLI/SLO: (1) performance — 30-day error budget calculations are expensive; pre-computing them prevents slow dashboard loads and Prometheus overload, (2) consistency — alerting rules and dashboard panels reference the same recording rule metric, eliminating discrepancies between what fires an alert and what the dashboard shows, (3) reusability — multiple dashboards and alerts reference one recording rule. This is why the Google SRE Workbook recommends recording rules for all SLO calculations.","context":{}},
    {"level":4,"diff":1,"scenario":4,"q":"A Cloud SQL maintenance window is configured for Sunday 02:00-06:00 UTC. What happens during a Cloud SQL maintenance event?","opts":["GCP applies patches to the Cloud SQL proxy running in your GKE cluster — the database itself is unaffected","GCP performs instance maintenance (OS patches, database minor version updates) which may cause a brief connection reset — typically 1-2 minutes of unavailability for non-HA instances, or a fast failover for HA instances","The Cloud SQL instance is completely unavailable for the entire 4-hour window","Maintenance only affects the standby instance — the primary remains fully available throughout","Cloud SQL maintenance is always zero-downtime — no connection interruption occurs"],"ans":1,"fb":"Cloud SQL maintenance involves OS patching and minor database version updates. For non-HA instances: a brief restart causes 1-2 minutes of unavailability — connections are dropped and must be retried. For HA instances: maintenance triggers a failover to the standby, causing a brief connection interruption (typically under 60 seconds) followed by automatic reconnection. Applications must handle transient connection failures gracefully via HikariCP connection validation and retry logic. The maintenance window defines when GCP is allowed to schedule this, not a guaranteed start time.","context":{"Maintenance window":"Sunday 02:00-06:00 UTC","HA instance downtime":"~60 seconds (failover)","Non-HA instance downtime":"1-2 minutes"}},
    {"level":4,"diff":1,"scenario":4,"q":"Your Cloud SQL instance has SSL certificates that expire in 30 days. What is the impact if the certificates are not rotated before expiry?","opts":["No impact — Cloud SQL automatically generates new certificates and updates all clients","The Cloud SQL Auth Proxy stops accepting connections — all database connections fail","Connections using SSL enforcement will fail once the server certificate expires. Applications using the Cloud SQL Auth Proxy are unaffected (proxy manages its own mTLS), but applications connecting directly with SSL mode=VERIFY_CA or VERIFY_FULL will fail","Only new connections fail — existing long-running connections remain valid until closed","SSL expiry triggers automatic Cloud SQL instance recreation — no manual action needed"],"ans":2,"fb":"Cloud SQL server SSL certificates have an expiry date. The Cloud SQL Auth Proxy manages its own certificate-based authentication independently — applications using the Auth Proxy are not affected by server SSL cert expiry. However, applications connecting directly to Cloud SQL with ssl_mode=VERIFY_CA or VERIFY_FULL will reject connections to a server presenting an expired certificate. The rotation procedure: use `gcloud sql ssl server-ca-certs create`, download new certificates, update client configurations, and verify connectivity before the old cert expires.","context":{"Certificate expiry":"30 days","Affected connections":"Direct SSL connections with VERIFY_CA/VERIFY_FULL","Unaffected":"Cloud SQL Auth Proxy connections"}},
    {"level":4,"diff":1,"scenario":4,"q":"After a Cloud SQL maintenance event, the application pods report HikariCP connection errors: 'Connection is not available, request timed out after 30000ms'. The Cloud SQL instance is healthy. What is the most likely cause?","opts":["The Cloud SQL instance requires a manual restart after maintenance — run `gcloud sql instances restart`","HikariCP's idle connections were dropped by Cloud SQL during the maintenance restart. HikariCP did not detect the stale connections and is attempting to use them. Enable `connection-test-query` or `keepalive-time` to validate connections before use","The maintenance event changed the Cloud SQL instance's IP address — update the JDBC URL","HikariCP pool size is too small for post-maintenance reconnection surge — increase maximumPoolSize","The Cloud SQL Auth Proxy needs to be restarted after every Cloud SQL maintenance event"],"ans":1,"fb":"During a Cloud SQL maintenance restart, the database server closes all existing connections. HikariCP pools idle connections — connections established before maintenance remain in the pool but are now dead (server-side closed). When the application tries to use a pooled connection, the attempt fails. HikariCP's connection validation settings prevent this: `connectionTestQuery=SELECT 1` validates connections before returning from the pool, `keepaliveTime=60000` proactively tests idle connections, and `idleTimeout` evicts connections that have been idle too long.","context":{"HikariCP error":"Connection is not available, request timed out after 30000ms","Cloud SQL status":"Healthy, restarted after maintenance","Root cause":"Stale pooled connections not detected by HikariCP"}},
    {"level":4,"diff":2,"scenario":4,"q":"You are planning a Cloud SQL minor version upgrade during a maintenance window. The production database has 150 active connections from 6 Spring Boot service deployments. What is the complete preparation checklist before the maintenance window?","opts":["Verify the new version is compatible and schedule the upgrade — Cloud SQL handles everything else","Verify application compatibility with the new version, confirm HikariCP is configured to retry connections (connectionTestQuery, initializationFailTimeout), test the upgrade in staging under load, prepare a rollback plan (create a pre-upgrade backup), notify stakeholders, monitor during the window with dashboards showing connection count and error rate","Drain all application connections before the upgrade by scaling deployments to 0 replicas, then upgrade, then scale back up","Only upgrade during business hours so the team is available — never do database maintenance at night","Run `gcloud sql instances patch` and monitor — Cloud SQL upgrades are always backward compatible and require no preparation"],"ans":1,"fb":"A Cloud SQL minor version upgrade requires full preparation: (1) compatibility testing in staging with the same application versions, (2) HikariCP reconnection validation (connectionTestQuery, keepaliveTime) to handle the brief connection reset, (3) pre-upgrade backup for rollback, (4) stakeholder notification (support teams, on-call), (5) dashboard preparation (connection count, error rate, HikariCP pool metrics), (6) rollback plan documentation. Scaling to 0 replicas is unnecessary if applications are configured for reconnection and the service has appropriate PDBs.","context":{"Active connections":"150","Services affected":"6 Spring Boot deployments"}},
    {"level":4,"diff":2,"scenario":4,"q":"A Cloud SQL HA instance failover occurs during peak hours due to a zone outage. What is the expected sequence of events for application connections, and what metric confirms the failover completed successfully?","opts":["Failover is transparent — no connections are dropped and applications experience no errors","The primary becomes unavailable; Cloud SQL promotes the standby within ~60 seconds; existing connections to the old primary are dropped and return connection errors; after promotion, new connections establish to the promoted instance at the same IP. Monitor `cloudsql.googleapis.com/database/postgresql/num_backends` returning to normal levels and application error rate returning to baseline","Failover requires manual intervention — run `gcloud sql instances failover` to complete the promotion","During HA failover, all writes are queued and replayed after the standby is promoted — no data loss and no errors","The Cloud SQL load balancer automatically routes connections to the standby during failover — no connections are dropped"],"ans":1,"fb":"Cloud SQL HA failover sequence: (1) GCP detects primary failure (~10-30s), (2) standby is promoted to primary (~30-60s total from failure), (3) the Cloud SQL IP address is remapped to the promoted instance, (4) existing connections to the old primary are dropped — applications see connection errors during this window. After promotion, applications reconnect (HikariCP eviction + reconnect). The Cloud SQL IP remains the same (it is a virtual IP), so no JDBC URL changes are needed. Monitor num_backends recovering and application error rate returning to baseline.","context":{"HA failover duration":"~60 seconds total","Connection behavior":"Existing connections dropped, new connections succeed after promotion"}},
    {"level":4,"diff":2,"scenario":4,"q":"You need to schedule Cloud SQL SSL certificate rotation across 6 production databases without causing downtime. What is the correct rotation sequence?","opts":["Delete old certificates and create new ones simultaneously — brief downtime is unavoidable","Phase 1: Create new server CA certs (gcloud sql ssl server-ca-certs create) — old certs still valid. Phase 2: Download new certs and update client-side certificate bundles in all services (deploy with both old and new certs in the bundle). Phase 3: Rotate the active cert (gcloud sql ssl server-ca-certs rotate) — server switches to new cert. Phase 4: Remove old cert from client bundles in a subsequent deployment","Update the JDBC connection string to disable SSL verification during rotation, rotate, then re-enable","Rotate all 6 databases simultaneously in a 2-hour maintenance window — parallel rotation is fastest","SSL rotation only requires a kubectl rollout restart of application pods — no Cloud SQL changes needed"],"ans":1,"fb":"Zero-downtime SSL rotation requires a two-phase approach: (1) create new certificates while old ones remain valid — both are active simultaneously, (2) update client certificate bundles to include the new cert (deploy updated ConfigMaps/Secrets), (3) rotate the active server cert (old cert is now the 'previous' cert, still accepted during transition), (4) remove old cert from client bundles. This ensures no moment where the server presents a cert the client doesn't trust, or the client presents a cert the server doesn't accept. Cloud SQL supports this overlap period.","context":{"Certificate overlap":"Both old and new certs valid during transition","Tool":"gcloud sql ssl server-ca-certs create && rotate"}},
    {"level":4,"diff":3,"scenario":4,"q":"A Cloud SQL instance has been running at 95% storage capacity for 3 days. Auto-resize is enabled. A developer asks whether this is a problem since auto-resize will handle it. What is the complete risk assessment?","opts":["No risk — auto-resize is designed exactly for this situation and will expand storage automatically","Three risks: (1) auto-resize is triggered by storage crossing a threshold — if a large write burst hits before resize completes, the instance can run out of space causing writes to fail mid-transaction; (2) auto-resize permanently increases the disk size, increasing monthly costs; (3) at 95% with auto-resize set to a fixed increment, rapid growth may trigger multiple resize cycles. Action: proactively resize to add headroom, investigate what is growing (tables, indexes, WAL, bloat), and set an alert at 80% to catch this earlier","The only risk is cost — auto-resize increases disk size and cannot be reversed. No operational risk exists","Auto-resize causes a brief Cloud SQL restart — at 95% capacity this is already scheduled and unavoidable","The database will become read-only at 100% storage — auto-resize prevents this automatically with no risk"],"ans":1,"fb":"Auto-resize mitigates the storage crisis but does not eliminate risk. Key risks: (1) timing gap — auto-resize triggers at a threshold but takes time; a sudden large write (batch import, log explosion) can exhaust space before resize completes, causing disk-full errors that abort transactions and corrupt partial writes; (2) cost — disk grows permanently (Cloud SQL storage cannot shrink); (3) root cause — 95% may indicate a runaway process (table bloat, WAL accumulation, missing vacuum) that will consume new space quickly. The alert at 80% is the correct prevention — 95% is already in the danger zone.","context":{"Current storage":"95% capacity","Auto-resize":"Enabled","Duration at 95%":"3 days"}},
    {"level":4,"diff":3,"scenario":4,"q":"During a planned Cloud SQL major version upgrade (PostgreSQL 13 → 15), the upgrade fails at 40% completion. The Cloud SQL instance is showing status 'MAINTENANCE'. What is the immediate action and recovery path?","opts":["Run `gcloud sql instances patch --database-version=POSTGRES_15` again to retry the upgrade","Wait for the MAINTENANCE status to resolve — Cloud SQL will either complete the upgrade or automatically roll back to the previous version. Do not attempt manual intervention during MAINTENANCE status. Monitor `gcloud sql instances describe` for status changes. If the instance stays in MAINTENANCE for more than 2 hours, contact GCP support with the instance name and operation ID from `gcloud sql operations list`","Delete the instance and restore from the pre-upgrade backup — this is the safest recovery path","Scale all application pods to 0 replicas to stop database connections, allowing the upgrade to complete","SSH into the Cloud SQL instance and run PostgreSQL upgrade scripts manually"],"ans":1,"fb":"Cloud SQL MAINTENANCE status means GCP is performing an operation — it is not accessible for management commands. During a failed upgrade, Cloud SQL will attempt to roll back automatically. Manual intervention (patching, deleting) during MAINTENANCE can cause data loss or undefined state. The correct action: monitor via `gcloud sql operations list --instance=INSTANCE_NAME` for the operation status, and contact GCP support if it does not resolve within a reasonable window. Always take a manual backup before major version upgrades (in addition to automated backups) precisely for this scenario.","context":{"Instance status":"MAINTENANCE","Upgrade":"PostgreSQL 13 → 15","Progress":"Failed at ~40%"}},
    {"level":4,"diff":3,"scenario":4,"q":"You discover that HikariCP is configured with `minimumIdle=50` and `maximumPoolSize=50` across 8 replicas of the payment service, connecting to a Cloud SQL instance with `max_connections=200`. After a recent scale-up to 12 replicas, the service starts throwing 'FATAL: remaining connection slots are reserved for non-replication superuser connections'. What is the root cause and the correct fix?","opts":["Increase Cloud SQL max_connections to 500 — the current limit is too low for the workload","The fixed pool size (minimumIdle=maximumPoolSize=50) means each replica holds 50 connections open always. At 12 replicas: 12 × 50 = 600 connections, far exceeding Cloud SQL's 200 max_connections. Fix: reduce maximumPoolSize per replica (e.g. floor(180 / 12) = 15), set minimumIdle lower than maximumPoolSize, or introduce a connection pooler (PgBouncer) as a proxy to multiplex application connections onto fewer database connections","Set maximumPoolSize=200 and minimumIdle=0 — this allows dynamic scaling up to the database limit","Enable Cloud SQL connection pooling in the GCP console — this handles connection limits automatically","The error means Cloud SQL is overloaded — scale up the Cloud SQL instance tier to increase connection capacity"],"ans":1,"fb":"Cloud SQL max_connections is a database-level hard limit. With minimumIdle=maximumPoolSize=50 (eager pool fill), each replica holds exactly 50 connections open — no idle eviction occurs. 12 replicas × 50 = 600, far exceeding 200. The error fires because Cloud SQL reserves some slots for superusers. Solutions: (1) reduce maximumPoolSize to floor((max_connections - reserved) / replicas) — leave headroom for replicas added by HPA, (2) PgBouncer in transaction mode multiplexes 600 application connections onto 50 database connections, (3) set minimumIdle < maximumPoolSize to allow pool shrinking when pods are idle. max_connections increasing on Cloud SQL requires an instance restart and is a less scalable long-term solution.","context":{"minimumIdle":"50","maximumPoolSize":"50","Replicas":"12","Total connections":"12 × 50 = 600","Cloud SQL max_connections":"200","Error":"FATAL: remaining connection slots are reserved for non-replication superuser connections"}}
  ]
};
